using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace Pinnacle.Transactions.Lovely
{
    public partial class OTPaySlip : Form,ToolStripAccess
    {
        private static OTPaySlip _instance;
        public static OTPaySlip Instance
        {
            get
            {
                if (_instance == null)
                    _instance = new OTPaySlip();
                return _instance;
            }
        }
        public OTPaySlip()
        {
            InitializeComponent();
          Class.Users.IPADDRESS = GenFun.GetLocalIPAddress();
            Class.Users.CREATED = Convert.ToDateTime(System.DateTime.Now.ToString("dd-MMM-yyyy") + " " + System.DateTime.Now.ToLongTimeString());
            Class.Users.SysDate = Convert.ToString(System.DateTime.Now.ToString("dd-MM-yyyy"));
            Class.Users.SysTime = Convert.ToString(DateTime.Now.ToShortTimeString().ToString());
            GlobalVariables.HeaderName.Text = Class.Users.ScreenName;
            GlobalVariables.CurrentForm = this;
          

        }


        Models.Master mas = new Models.Master();
        ListView allip = new ListView();
        Models.UserRights sm = new Models.UserRights(); ListView listfilter = new ListView(); ListView listfilter2 = new ListView();
        int i = 0;
       
        DataTable dtprint0 = new DataTable();
        DataTable dtprint1 = new DataTable();
        DataTable dtprint2 = new DataTable();
        DataTable dtprint3 = new DataTable(); DataTable dtprint4 = new DataTable();
        DataTable dtgeneral = new DataTable();
        DataTable reversedDt = new DataTable();
        DataTable reversedDt1 = new DataTable();
        DataTable reversedDt2 = new DataTable();
        DataTable reversedDt3 = new DataTable();
        public void News()
        {
           
            crystalReportViewer1.ReportSource = null; crystalReportViewer1.Refresh();
           
            txtsearch1.Select(); 
            combopayperiod.SelectedIndex = -1; combopayperiod.Text = "";
            comboband.SelectedIndex = -1; comboband.Text = ""; combotypename.SelectedIndex = -1; combotypename.Text = "";
            combogender.SelectedIndex = -1; combogender.Text = ""; combopayperiod.SelectedIndex = -1; combopayperiod.Text = ""; combobranch.SelectedIndex = -1; combobranch.Text = "";
            panel5.BackColor = Class.Users.BackColors;
            panel6.BackColor = Class.Users.BackColors;
            listView2.Font = Class.Users.FontName;          
            this.BackColor = Class.Users.BackColors;
            this.Font = Class.Users.FontName;
            lblprogross4.BackColor = Class.Users.BackColors;
            lblprogross4.Font = Class.Users.FontName; 
           
        }

        private void ALLSalarySlip_Load(object sender, EventArgs e)
        {
            empty();
            companyload1(); bandload1(); typenameload1(); genderoand(); paypreiodoand();

            txtsearch1.Select();combostatement.SelectedIndex = 0;
        }
        string folderLocation = "C:\\PaySlip-Download\\";
        private string BuildEmployeeQuery(bool isHO, bool isGroup4)
        {
            string extraCondition = "";

            if (!isHO)
            {
                extraCondition = " AND C.LOCPLACE <> 1544713937669 ";
            }

            // GROUP4 condition (if any special logic needed)
            if (isGroup4)
            {
                // add extra filters here if needed
            }           

            string query = @$"SELECT aa.HREMPLOYMASTID, AA.IDCARD, B.OIDNO as MIDCARD, C.FNAME,'{Class.Users.HCompcode}' COMPCODE, aa.PAYPERIOD, aa.BRANCH, aa.BANDid, aa.GENDER, aa.TYPENAME  FROM ( SELECT aa.*,DENSE_RANK() OVER (PARTITION BY AA.GENDER,AA.BRANCH,AA.BANDID ORDER BY AA.EMPNAME) SNO   FROM (     SELECT C.HREMPLOYMASTID, A.BRANCH, D.BANDID, C.GENDER,TO_NUMBER(B.IDCARD) IDCARD, C.FNAME EMPNAME,G.DESIGNATION MACHINENAME, F.SNO1 AS PAYPERIOD,'{combotypename.Text}' TYPENAME  FROM OTSTAMENT  A     JOIN HREMPLOYDETAILS B ON A.EMPID = B.IDCARD JOIN HREMPLOYMAST C ON B.HREMPLOYMASTID = C.HREMPLOYMASTID   JOIN HRBANDMAST D ON B.BAND = D.HRBANDMASTID JOIN MACHINEMAST E ON E.MACHINEMASTID = B.MACNAME   JOIN WEEKLYPAYFRQ F ON A.WEEKCODE = F.PAYPERIOD AND A.FROMDATE = F.STDT JOIN HRDESIGNATIONMAST G ON G.HRDESIGNATIONMASTID = B.DESIGNATION  JOIN GTCOMPMAST H ON H.GTCOMPMASTID = C.COMPCODE   WHERE F.SNO1 = '{combopayperiod.Text}'  AND (A.BRANCH = '{combobranch.Text}' OR '{combobranch.Text}' = 'ALL')    AND (D.BANDID = '{comboband.Text}' OR '{comboband.Text}' = 'ALL')  AND (C.GENDER = '{combogender.Text}' OR '{combogender.Text}' = 'ALL')  " + extraCondition + @" ) aa   ) AA JOIN HREMPLOYDETAILS B ON AA.IDCARD = B.IDCARD JOIN HREMPLOYMAST C ON C.HREMPLOYMASTID = B.HREMPLOYMASTID ORDER BY AA.IDCARD";
            return query;
        }
        public void GridLoad()
        {
            i = 1;
            if (combopayperiod.Text != "")
            {
                string sel1 = "";
                listView2.Items.Clear(); listfilter2.Items.Clear(); allip.Items.Clear();
                bool isHO = Class.Users.HUserName == "HO";
                bool isGroup4 = Class.Users.HUserName == "GROUP4";
                string query = BuildEmployeeQuery(isHO, isGroup4);     
                DataSet ds1 = Utility.ExecuteSelectQuery(query, "HREMPLOYMAST");
                DataTable dt1 = ds1.Tables["HREMPLOYMAST"];
               
                if (dt1.Rows.Count > 0)
                {
                    listView2.BeginUpdate();
                    foreach (DataRow myRow in dt1.Rows)
                    {
                        ListViewItem list = new ListViewItem();


                        list.SubItems.Add(i.ToString());
                        list.SubItems.Add(myRow["HREMPLOYMASTID"].ToString());
                        list.SubItems.Add(myRow["IDCARD"].ToString());
                        list.SubItems.Add(myRow["MIDCARD"].ToString());
                        list.SubItems.Add(myRow["FNAME"].ToString());
                        list.SubItems.Add(myRow["COMPCODE"].ToString());
                        list.SubItems.Add(myRow["PAYPERIOD"].ToString());
                        list.BackColor = (i % 2 == 0) ? Color.White : Color.WhiteSmoke;
                        this.listfilter2.Items.Add((ListViewItem)list.Clone());
                        listView2.Items.Add(list); lbllistviewcount.Refresh();
                        lbllistviewcount.Text = "Total Count    : " + listView2.Items.Count;
                        i++;
                    }
                    listView2.EndUpdate();
                }
                else
                {
                    mas.pop("No Data Found", "","");
                }
            }
            else
            {
                mas.pop("Pls Select Mandatory Fields","","");
            }
        }
        void empty()
        {
            txtsearch1.Text = "";

            if (dtprint1 != null || dtprint0 != null)
            {
               allip.Items.Clear(); 
                 dtprint0 = null; dtprint1 = null; dtprint2 = null; dtprint3 = null;
                lblprogross4.Visible = false;
                Cursor = Cursors.Default;chkall.Checked = false;
                txtsearch1.Select();

            }
            
        }



        public void companyload1()
        {
            try
            {
                string sel = "SELECT '' BRANCH FROM DUAL  union SELECT A.BRANCHNAME BRANCH FROM BRANCHMAST A UNION SELECT 'ALL' BRANCH FROM DUAL";
                DataSet ds1 = Utility.ExecuteSelectQuery(sel, "BRANCHMAST");
                DataTable dt1 = ds1.Tables["BRANCHMAST"];
                combobranch.DisplayMember = "BRANCH";
                combobranch.ValueMember = "BRANCH";
                combobranch.DataSource = dt1;
                
            }
            catch (Exception ex)
            {
                 mas.pop("Compcode", ex.Message, "");
            }

        }
        
        public void bandload1()
        {
            try
            {
                string sel = "SELECT '' BANDID FROM DUAL  union SELECT A.BANDID FROM HRBANDMAST A WHERE A.MACTIVE = 'T' UNION SELECT 'ALL' BANDID FROM DUAL";
                DataSet ds1 = Utility.ExecuteSelectQuery(sel, "HRBANDMAST");
                DataTable dt1 = ds1.Tables["HRBANDMAST"];
                comboband.DisplayMember = "BANDID";
                comboband.ValueMember = "BANDID";
                comboband.DataSource = dt1;
            }
            catch (Exception ex)
            {
                mas.pop("BandLoad", ex.Message, "");
            }

        }

        public void typenameload1()
        {
            try
            {
                string sel = "SELECT '' TYPE FROM DUAL  union SELECT 'SALARY BANK-STATEMENT' TYPE FROM DUAL UNION SELECT 'SALARY PERMANENT-CASH STATEMENT' TYPE FROM DUAL UNION SELECT 'SALARY PERMANENT-BANK & CASH STATEMENT' TYPE FROM DUAL UNION SELECT 'SALARY TRAINEE-STATEMENT' TYPE FROM DUAL UNION SELECT 'ALL' TYPE FROM DUAL";
                DataSet ds1 = Utility.ExecuteSelectQuery(sel, "DUAL");
                DataTable dt1 = ds1.Tables["DUAL"];
                combotypename.DisplayMember = "TYPE";
                combotypename.ValueMember = "TYPE";
                combotypename.DataSource = dt1;
            }
            catch (Exception ex)
            {
                mas.pop("TypenamerLoad", ex.Message, "");
            }

        }

        
        public void genderoand()
        {
            try
            {
                string sel = "SELECT '' GENDER FROM DUAL  union  SELECT 'MALE' GENDER FROM DUAL UNION SELECT 'FEMALE' GENDER FROM DUAL UNION SELECT 'ALL' GENDER FROM DUAL";
                DataSet ds1 = Utility.ExecuteSelectQuery(sel, "DUAL");
                DataTable dt1 = ds1.Tables["DUAL"];
                combogender.DisplayMember = "GENDER";
                combogender.ValueMember = "GENDER";
                combogender.DataSource = dt1;
            }
            catch (Exception ex)
            {
                mas.pop("GenderLoad", ex.Message, "");
            }

        }

        public void paypreiodoand()
        {
            try
            {
             
                string sel = " SELECT PAYPERIOD,FINYR from(  SELECT '' PAYPERIOD,'' FINYR FROM DUAL  union SELECT A.SNO1  as  PAYPERIOD,a.FINYR FROM WEEKLYPAYFRQ  A ) order by FINYR desc";
                DataSet ds1 = Utility.ExecuteSelectQuery(sel, "MONTHLYPAYFRQ");
                DataTable dt1 = ds1.Tables["MONTHLYPAYFRQ"];
                combopayperiod.DisplayMember = "PAYPERIOD";
                combopayperiod.ValueMember = "PAYPERIOD";
                combopayperiod.DataSource = dt1;
            }
            catch (Exception ex)
            {
                mas.pop("PayPreiodLoand", ex.Message, "");
            }

        }
        ReportDocument cryRpt = new ReportDocument();
        //Report.Lovely.ALLPaySlip rd = new Report.Lovely.ALLPaySlip();
        Report.Lovely.OTReport rd1 = new Report.Lovely.OTReport();

        string ORD = "";
        byte[] bytes; 
        private bool IsGroupUser(string userName)
        {
            var groupUsers = new HashSet<string> { "GROUP1", "GROUP2", "GROUP3", "GROUP4" };
            return groupUsers.Contains(userName);
        }
        public void Pdfs()
        {
            
               
           
        }

        private void listView2_ItemActivate(object sender, EventArgs e)
        {
            Class.Users.UserTime = 0;
            try
            {
               
                    string sel0 = ""; Cursor = Cursors.WaitCursor;       
                    string empId = listView2.SelectedItems[0].SubItems[3].Text;
                    string payPeriod = listView2.SelectedItems[0].SubItems[7].Text;
                    string compcode = Class.Users.HCompcode;
                    if (IsGroupUser(Class.Users.HUserName))
                    {
                        dtprint1 = GetPayroll_Group(empId, payPeriod);
                    }
                    else
                    {
                        dtprint1 = GetPayroll_NotGroup(empId, payPeriod);
                    }


                    if (dtprint1.Rows.Count > 0)
                    {
                        if (listView2.SelectedItems.Count == 0)
                        {
                            MessageBox.Show("Please select a row.");
                            return;
                        }
                       
                        dtprint2 = GetPayroll_Signature(empId, compcode);
                        dtprint3 = GetPayroll_OT1(empId, payPeriod);
                        dtprint4 = GetPayroll_OT(empId, payPeriod);
                    crystalReportViewer1.ReportSource = null;
                    crystalReportViewer1.Refresh();
                    
                    rd1.Database.Tables["DataTable1"].SetDataSource(dtprint1);
                    rd1.Database.Tables["DataTable2"].SetDataSource(dtprint2);
                    rd1.Database.Tables["DataTable3"].SetDataSource(dtprint3);
                    rd1.Database.Tables["DataTable4"].SetDataSource(dtprint4);

                    rd1.Refresh();

                    crystalReportViewer1.ReportSource = rd1;
                    crystalReportViewer1.RefreshReport();


                }
                    else
                    {
                        mas.pop($"No Data Found.Record Count :{dtprint1.Rows.Count.ToString()}", Class.Users.HUserName, "");
                       
                    }
                //}
            }
            catch(Exception ex)
            {
                mas.pop(ex.Message, Class.Users.HUserName, "");
               
            }
            finally
            {
                Cursor = Cursors.Default;
            }


        }
        private DataTable GetPayroll_OT1(string empId, string paypreiod)
        {

            string sel2 = "SELECT A.FROMDATE||' - '||A.TODATE AS  PERIOD,A.BUYER OTMIN,ROUND(((((BASIC+DA+SPL)/26)/8)/60)*2*A.BUYER,2) OTAMT,  CASE WHEN B.ESI = 'YES' THEN ROUND(ROUND(((((BASIC+DA+SPL)/26)/8)/60)*2*A.BUYER,2)*0.75/100,2) ELSE 0 END ESI,  ROUND(((((BASIC+DA+SPL)/26)/8)/60)*2*A.BUYER,2) - CASE WHEN B.ESI = 'YES' THEN ROUND(ROUND(((((BASIC+DA+SPL)/26)/8)/60)*2*A.BUYER,2)*0.75/100,2) ELSE 0 END NETAMOUNT FROM OTSTAMENT A JOIN HREMPLOYDETAILS B ON A.EMPMAID = B.HREMPLOYMASTID JOIN WEEKLYPAYFRQ C ON C.STDT = A.FROMDATE  WHERE B.IDACTIVE = 'YES'  AND  C.SNO1 ='" + paypreiod + "' AND B.IDCARD= '" + empId + "' AND A.BUYER > 0  ORDER BY A.FROMDATE";
            DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLEMP");

            return ds2.Tables["ASPTBLEMP"];
        }
        private DataTable GetPayroll_OT(string empId, string payPeriod)
        {
           string query = @$"SELECT AA.EMPID,AA.FNAME,AA.DOCDATE, CASE WHEN AA.COMTEMP IS NULL AND AA.SHIFTCNT = 0 THEN 'Absent' ELSE AA.COMTEMP END COMTEMP,CASE WHEN AA.STEMP IS NULL AND AA.SHIFTCNT = 0 THEN 'Absent' ELSE AA.STEMP END STEMP ,CASE WHEN AA.SHIFTCNT = 0 AND(AA.OD > 0 OR AA.EL > 0) THEN DECODE(AA.OD,1,0,AA.OD)+DECODE(AA.EL, 1, 0, AA.EL) ELSE CASE WHEN AA.SHIFTCNT < 1 THEN AA.SHIFTCNT + DECODE(AA.OD, 1, 0, AA.OD) + DECODE(AA.EL, 1, 0, AA.EL) ELSE AA.SHIFTCNT END END SHIFTCNT  , AA.OT / 60 OT,CASE WHEN AA.INDT1 IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(AA.INDT1,'DD/MM/YYYY HH24:MI:SS'),'HH24:MI:SS') ELSE '' END INTIME,CASE WHEN AA.OUTDT1 IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(AA.OUTDT1,'DD/MM/YYYY HH24:MI:SS'),'HH24:MI:SS') ELSE '' END OUTTIME, CASE WHEN AA.INDT1 IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(AA.INDT1,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY') ELSE '' END INDATE,  CASE WHEN AA.OUTDT1 IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(AA.OUTDT1,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY') ELSE '' END OUTDATE,TO_CHAR(AA.DOCDATE, 'Day') DOCDAY FROM(SELECT AA.EMPID, AA.FNAME, AA.DOCDATE, AA.COMTEMP, AA.STEMP, AA.SHIFTCNT, AA.OT, AA.IDCARD, AA.INDT1, AA.OUTDT1,  NVL((    SELECT SUM(A.OLHDCNT)  SHIFTCNT FROM HRONDUTYDET  A, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E WHERE A.IDCARD = D.HREMPLOYDETAILSID AND B.WORKNATURE = E.BRANCHMASTID  AND B.HREMPLOYMASTID = D.HREMPLOYMASTID AND A.ODATE = AA.DOCDATE  AND E.BRANCHNAME = AA.BRANCH AND D.IDCARD = AA.EMPID ), 0) OD, NVL((SELECT(0 - SUM(A.STKOPBAL)) SHIFTCNT FROM HRLEAVEREGMAST A  WHERE A.LEAVETYPE = 'EL' AND A.LTYPE <> 'ENC'  AND A.LRDATE = AA.DOCDATE AND A.IDNOCHK = AA.IDCARD  GROUP BY A.IDNOCHK, A.LRDATE),0) EL,NVL((SELECT AA.LHDCNT     FROM HRLEAVEREQMAST A, HRLEAVEREQDETAIL  AA, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E WHERE A.HRLEAVEREQMASTID = AA.HRLEAVEREQMASTID AND A.IDCARD = D.HREMPLOYDETAILSID AND B.WORKNATURE = E.BRANCHMASTID AND A.LTYPE = 'ML' AND AA.LDATE = AA.DOCDATE AND  E.BRANCHNAME = AA.BRANCH AND D.IDCARD = AA.EMPID AND B.HREMPLOYMASTID = D.HREMPLOYMASTID ),0) ML FROM( SELECT A.EMPID, B.FNAME, A.DOCDATE, '' COMTEMP, '' STEMP, A.SHIFTCNT, A.OT, A.EMPID IDCARD, TO_CHAR(A.DOCDATE, 'DD/MM/YYYY') || ' 00:00:00' INDT1, TO_CHAR(A.DOCDATE, 'DD/MM/YYYY') || ' 00:00:00' OUTDT1, B.HREMPLOYMASTID, E.BRANCHNAME BRANCH FROM LOGINLOGOUTREPORT A, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E, GTCOMPMAST F, HRBANDMAST G WHERE A.EMPID = D.IDCARD AND D.BAND = G.HRBANDMASTID AND D.IDCARD = '{empId}' AND A.DOCDATE BETWEEN (SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE(A.SNO1 ='{payPeriod}')) AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE(A.SNO1 = '{payPeriod}')) AND B.HREMPLOYMASTID = D.HREMPLOYMASTID AND E.BRANCHMASTID = B.WORKNATURE AND B.COMPCODE = F.GTCOMPMASTID AND NOT EXISTS(SELECT 'X' FROM( SELECT A.EMPID, B.FNAME, A.DOCDATE, A.TEMPLATE COMTEMP, A.TEMPL STEMP, A.SHIFTCNT, A.OT, A.EMPID IDCARD, CASE WHEN A.INTIME IS NOT NULL AND A.INDT IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(A.INDT || ' ' || A.INTIME, 'DD/MM/YY HH24:MI:SS'), 'DD/MM/YYYY HH24:MI:SS') ELSE '' END INDT1, CASE WHEN A.OUTTIME IS NOT NULL AND A.OUTDT IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(A.OUTDT || ' ' || A.OUTTIME, 'DD/MM/YY HH24:MI:SS') + NUMTODSINTERVAL(A.OT, 'MINUTE'), 'DD/MM/YYYY HH24:MI:SS') ELSE '' END OUTDT1,B.HREMPLOYMASTID FROM BHDATTA A, HREMPLOYMAST B, HREMPLOYDETAILS D WHERE A.EMPMAID = B.HREMPLOYMASTID AND D.IDCARD = '{empId}' AND A.DOCDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID UNION SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, A.ODATE DOCDATE, 'On Duty' COMTEMP, 'On Duty' STEMP, CASE WHEN A.OHDAY = 'I & II' THEN 1 ELSE 0 END SHIFTCNT, 0 OT, TO_NUMBER(D.IDCARD) IDCARD, TO_CHAR(A.ODATE, 'DD/MM/YYYY') INDT1, TO_CHAR(A.ODATE, 'DD/MM/YYYY') OUTDT1, B.HREMPLOYMASTID FROM HRONDUTYDET  A, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E WHERE A.IDCARD = D.HREMPLOYDETAILSID AND B.WORKNATURE = E.BRANCHMASTID AND A.OHDAY = 'I & II' AND A.ODATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(E.BRANCHNAME = '{combobranch.Text}' OR 'ALL' = '{combobranch.Text}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID UNION SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, A.DOCDATE, 'Leave' COMTEMP, 'Leave' STEMP, A.SHIFTCNT,0 OT, TO_NUMBER(D.IDCARD) IDCARD, TO_CHAR(A.DOCDATE, 'DD/MM/YYYY') INDT1, TO_CHAR(A.DOCDATE, 'DD/MM/YYYY') OUTDT1, B.HREMPLOYMASTID FROM(SELECT A.IDCARD, A.IDNOCHK, A.LRDATE DOCDATE, (0 - SUM(A.STKOPBAL)) SHIFTCNT FROM HRLEAVEREGMAST A WHERE A.LRDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') GROUP BY A.IDCARD, A.IDNOCHK, A.LRDATE HAVING(0 - SUM(A.STKOPBAL)) = 1) A, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E WHERE A.IDCARD = B.HREMPLOYMASTID AND B.WORKNATURE = E.BRANCHMASTID AND A.DOCDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID UNION SELECT DISTINCT A.EMPID, A.FNAME, A.DOCDATE, A.COMTEMP, A.STEMP, A.SHIFTCNT,     A.OT, A.IDCARD, A.INDT1, A.OUTDT1, A.HREMPLOYMASTID     FROM( SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, A.NHDATE DOCDATE, A.HOLCAT COMTEMP, A.HOLCAT STEMP, 1 SHIFTCNT, 0 OT, TO_NUMBER(D.IDCARD) IDCARD, TO_CHAR(A.NHDATE, 'DD/MM/YYYY') || ' 00:00:00' INDT1, TO_CHAR(A.NHDATE, 'DD/MM/YYYY') || ' 00:00:00' OUTDT1, B.HREMPLOYMASTID, E.BRANCHNAME BRANCH FROM HRNHDYDETAIL  A, HRNHDYBRANCHDET AA, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E, BHDATTA F, HRBANDMAST G WHERE A.HRNHDYDETAILID = AA.HRNHDYDETAILID AND B.WORKNATURE = E.BRANCHMASTID  AND D.BAND = G.HRBANDMASTID AND AA.BRANCHNAME = E.BRANCHNAME AND D.IDCARD = '{empId}' AND F.EMPID = D.IDCARD AND F.DOCDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND A.NHDATE >= D.DOJ AND(A.NHDATE < D.LASTWORKDAY OR D.LASTWORKDAY IS NULL) AND A.NHDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID ) A UNION SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, AA.LDATE DOCDATE, 'ML' COMTEMP, 'ML' STEMP, 0 SHIFTCNT, 0 OT, TO_NUMBER(D.IDCARD) IDCARD, TO_CHAR(AA.LDATE, 'DD/MM/YYYY') INDT1, TO_CHAR(AA.LDATE, 'DD/MM/YYYY') OUTDT1, B.HREMPLOYMASTID FROM HRLEAVEREQMAST A, HRLEAVEREQDETAIL  AA, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E, HRBANDMAST G WHERE A.HRLEAVEREQMASTID = AA.HRLEAVEREQMASTID AND A.IDCARD = D.HREMPLOYDETAILSID AND D.BAND = G.HRBANDMASTID AND B.WORKNATURE = E.BRANCHMASTID AND A.LTYPE = 'ML' AND D.IDCARD = '{empId}' AND AA.LDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID AND AA.LHDCNT = 1 ) X WHERE X.EMPID = A.EMPID AND X.DOCDATE = A.DOCDATE) UNION SELECT A.EMPID, B.FNAME, A.DOCDATE, A.TEMPLATE COMTEMP, A.TEMPL STEMP, A.SHIFTCNT, A.OT, A.EMPID IDCARD, CASE WHEN A.INTIME IS NOT NULL AND A.INDT IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(A.INDT || ' ' || A.INTIME, 'DD/MM/YY HH24:MI:SS'), 'DD/MM/YYYY HH24:MI:SS') ELSE '' END INDT1, CASE WHEN A.OUTTIME IS NOT NULL AND A.OUTDT IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(A.OUTDT || ' ' || A.OUTTIME, 'DD/MM/YY HH24:MI:SS') + NUMTODSINTERVAL(A.OT, 'MINUTE'), 'DD/MM/YYYY HH24:MI:SS') ELSE '' END OUTDT1, B.HREMPLOYMASTID, A.BRANCH FROM BHDATTA A, HREMPLOYMAST B, HREMPLOYDETAILS D, HRBANDMAST G WHERE A.EMPMAID = B.HREMPLOYMASTID AND D.BAND = G.HRBANDMASTID AND D.IDCARD = '{empId}' AND A.DOCDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID UNION SELECT DISTINCT A.EMPID, A.FNAME, A.DOCDATE, A.COMTEMP, A.STEMP, A.SHIFTCNT,     A.OT, A.IDCARD, A.INDT1, A.OUTDT1, A.HREMPLOYMASTID, A.BRANCH     FROM( SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, A.NHDATE DOCDATE, A.HOLCAT COMTEMP, A.HOLCAT STEMP, 1 SHIFTCNT, 0 OT, TO_NUMBER(D.IDCARD) IDCARD, TO_CHAR(A.NHDATE, 'DD/MM/YYYY') || ' 00:00:00' INDT1, TO_CHAR(A.NHDATE, 'DD/MM/YYYY') || ' 00:00:00' OUTDT1, B.HREMPLOYMASTID, E.BRANCHNAME BRANCH FROM HRNHDYDETAIL  A, HRNHDYBRANCHDET AA, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E, BHDATTA F, HRBANDMAST G WHERE A.HRNHDYDETAILID = AA.HRNHDYDETAILID AND B.WORKNATURE = E.BRANCHMASTID AND D.BAND = G.HRBANDMASTID  AND AA.BRANCHNAME = E.BRANCHNAME AND B.GENDER = '{combogender.Text}' AND G.BANDID = '{comboband.Text}' AND F.EMPID = D.IDCARD AND A.NHDATE >= D.DOJ AND(A.NHDATE < D.LASTWORKDAY OR D.LASTWORKDAY IS NULL) AND F.DOCDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND (SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND A.NHDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID ) A UNION SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, A.ODATE DOCDATE, 'On Duty' COMTEMP, 'On Duty' STEMP, CASE WHEN A.OHDAY = 'I & II' THEN 1 ELSE 0 END SHIFTCNT, 0 OT, TO_NUMBER(D.IDCARD) IDCARD, TO_CHAR(A.ODATE, 'DD/MM/YYYY') || ' 00:00:00' INDT1, TO_CHAR(A.ODATE, 'DD/MM/YYYY') || ' 00:00:00' OUTDT1, B.HREMPLOYMASTID, E.BRANCHNAME BRANCH FROM HRONDUTYDET  A, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E, HRBANDMAST G WHERE A.IDCARD = D.HREMPLOYDETAILSID AND B.WORKNATURE = E.BRANCHMASTID AND D.BAND = G.HRBANDMASTID AND A.OHDAY = 'I & II' AND D.IDCARD = '{empId}' AND A.ODATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID UNION SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, A.DOCDATE, 'EL' COMTEMP, 'EL' STEMP, A.SHIFTCNT, 0 OT, TO_NUMBER(D.IDCARD) IDCARD, TO_CHAR(A.DOCDATE, 'DD/MM/YYYY') || ' 00:00:00' INDT1, TO_CHAR(A.DOCDATE, 'DD/MM/YYYY') || ' 00:00:00' OUTDT1, B.HREMPLOYMASTID,E.BRANCHNAME BRANCH FROM(SELECT A.IDCARD, A.IDNOCHK, A.LRDATE DOCDATE, (0 - SUM(A.STKOPBAL)) SHIFTCNT FROM HRLEAVEREGMAST A WHERE A.LRDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') GROUP BY A.IDCARD, A.IDNOCHK, A.LRDATE HAVING(0 - SUM(A.STKOPBAL)) = 1) A, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E, HRBANDMAST G WHERE A.IDCARD = B.HREMPLOYMASTID AND B.WORKNATURE = E.BRANCHMASTID AND D.BAND = G.HRBANDMASTID  AND B.GENDER = '{combogender.Text}' AND G.BANDID = '{comboband.Text}' AND A.DOCDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(E.BRANCHNAME = '{combotypename.Text}' OR 'ALL' = '{combotypename.Text}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID UNION SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, AA.LDATE DOCDATE, 'ML' COMTEMP, 'ML' STEMP, 0 SHIFTCNT,0 OT, TO_NUMBER(D.IDCARD) IDCARD,TO_CHAR(AA.LDATE, 'DD/MM/YYYY') || ' 00:00:00' INDT1, TO_CHAR(AA.LDATE, 'DD/MM/YYYY') || ' 00:00:00' OUTDT1, B.HREMPLOYMASTID, E.BRANCHNAME BRANCH FROM HRLEAVEREQMAST A, HRLEAVEREQDETAIL  AA, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E, HRBANDMAST G WHERE A.HRLEAVEREQMASTID = AA.HRLEAVEREQMASTID AND A.IDCARD = D.HREMPLOYDETAILSID AND D.BAND = G.HRBANDMASTID AND B.WORKNATURE = E.BRANCHMASTID AND A.LTYPE = 'ML' AND AA.LHDCNT = 1  AND D.IDCARD = '{empId}' AND AA.LDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID ) AA ) AA JOIN HREMPLOYDETAILS BB ON BB.IDCARD = AA.EMPID JOIN HREMPLOYMAST DD ON BB.HREMPLOYMASTID = DD.HREMPLOYMASTID JOIN GTLOCMAST CC ON CC.GTLOCMASTID = DD.LOCPLACE WHERE AA.EMPID = '{empId}' AND NOT EXISTS(SELECT* FROM ( SELECT A.IDCARD FROM HREMPLOYDETAILS A, HREMPLOYMAST B, GTLOCMAST C, GTDEPTDESGMAST D  WHERE A.HREMPLOYMASTID = B.HREMPLOYMASTID AND B.LOCPLACE = C.GTLOCMASTID  AND A.DEPTNAME = D.GTDEPTDESGMASTID AND (D.DISPNAME IN ('CANTEEN','SECURITY','DRIVER')  OR C.LOCNAME = 'HEAD OFFICE' ) UNION SELECT A.IDCARD FROM HREMPLOYDETAILS A, HREMPLOYMAST B WHERE A.HREMPLOYMASTID = B.HREMPLOYMASTID AND B.EMPTYPE = 'Trainee' UNION SELECT A.IDCARD FROM HREMPLOYDETAILS A, HREMPLOYMAST B WHERE A.HREMPLOYMASTID = B.HREMPLOYMASTID AND A.LASTWORKDAY <= (SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') UNION SELECT A.IDCARD FROM HREMPLOYDETAILS A, HREMPLOYMAST B WHERE A.HREMPLOYMASTID = B.HREMPLOYMASTID AND A.DOJ > (SELECT MAX(A.ENDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}')  ) ZZ WHERE ZZ.IDCARD = AA.IDCARD ) ORDER BY 1,3";
            // this below query not workking  
            //string query = @$"SELECT AA.EMPID,AA.FNAME,AA.DOCDATE,CASE WHEN AA.COMTEMP IS NULL AND AA.SHIFTCNT = 0 THEN 'Absent' ELSE AA.COMTEMP END COMTEMP,CASE WHEN AA.STEMP IS NULL AND AA.SHIFTCNT = 0 THEN 'Absent' ELSE AA.STEMP END STEMP ,CASE WHEN AA.SHIFTCNT = 0 AND(AA.OD > 0 OR AA.EL > 0) THEN DECODE(AA.OD,1,0,AA.OD)+DECODE(AA.EL, 1, 0, AA.EL) ELSE CASE WHEN AA.SHIFTCNT < 1 THEN AA.SHIFTCNT + DECODE(AA.OD, 1, 0, AA.OD) + DECODE(AA.EL, 1, 0, AA.EL) ELSE AA.SHIFTCNT END END SHIFTCNT  , AA.OT / 60 OT,AA.IDCARD,AA.INDT1,AA.OUTDT1,AA.OD,AA.EL,AA.ML,(1 - (AA.SHIFTCNT + DECODE(AA.OD, 1, 0, AA.OD) + DECODE(AA.EL, 1, 0, AA.EL))) LOP,CASE WHEN AA.INDT1 IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(AA.INDT1,'DD/MM/YYYY HH24:MI:SS'),'HH24:MI:SS') ELSE '' END INTIME,CASE WHEN AA.OUTDT1 IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(AA.OUTDT1,'DD/MM/YYYY HH24:MI:SS'),'HH24:MI:SS') ELSE '' END OUTTIME, CASE WHEN AA.INDT1 IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(AA.INDT1,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY') ELSE '' END INDATE, CASE WHEN AA.OUTDT1 IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(AA.OUTDT1,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY') ELSE '' END OUTDATE, (SELECT B.ST FROM HRSHIFTTEMPDETAIL B, HRTEMPMAST C, HRCTEMPMAST D  WHERE B.TEMP = C.HRTEMPMASTID AND D.HRCTEMPMASTID = B.STEMPLATE AND D.TEMPDESC = AA.COMTEMP  AND UPPER(B.GCAT) = UPPER('BUYER')  AND B.APPLIEDON = (SELECT MAX(ABB.APPLIEDON) APPON FROM HRSHIFTTEMP AAA, HRSHIFTTEMPDETAIL ABB  WHERE AAA.HRSHIFTTEMPID = ABB.HRSHIFTTEMPID  AND ABB.TEMP = B.TEMP AND ABB.SHIFT = B.SHIFT AND B.STEMPLATE = ABB.STEMPLATE AND ABB.APPLIEDON <= TO_DATE(AA.DOCDATE)  AND UPPER(AAA.CAT) = UPPER('BUYER'))  AND B.APPLIEDON <= TO_DATE(AA.DOCDATE) AND C.TEMPNAME = AA.STEMP) ST, (SELECT B.ET FROM HRSHIFTTEMPDETAIL B, HRTEMPMAST C,HRCTEMPMAST D WHERE B.TEMP = C.HRTEMPMASTID AND D.HRCTEMPMASTID = B.STEMPLATE AND D.TEMPDESC = AA.COMTEMP AND UPPER(B.GCAT) = UPPER('BUYER') AND B.APPLIEDON = (SELECT MAX(ABB.APPLIEDON) APPON FROM HRSHIFTTEMP AAA, HRSHIFTTEMPDETAIL ABB  WHERE AAA.HRSHIFTTEMPID = ABB.HRSHIFTTEMPID AND ABB.TEMP = B.TEMP AND ABB.SHIFT = B.SHIFT AND B.STEMPLATE = ABB.STEMPLATE AND ABB.APPLIEDON <= TO_DATE(AA.DOCDATE) AND UPPER(AAA.CAT) = UPPER('BUYER')) AND B.APPLIEDON <= TO_DATE(AA.DOCDATE) AND C.TEMPNAME = AA.STEMP ) ET,TO_CHAR(AA.DOCDATE, 'Day') DOCDAY FROM(SELECT AA.EMPID, AA.FNAME, AA.DOCDATE, AA.COMTEMP, AA.STEMP, AA.SHIFTCNT, AA.OT, AA.IDCARD, AA.INDT1, AA.OUTDT1,  NVL((    SELECT SUM(A.OLHDCNT)  SHIFTCNT FROM HRONDUTYDET  A, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E WHERE A.IDCARD = D.HREMPLOYDETAILSID AND B.WORKNATURE = E.BRANCHMASTID  AND B.HREMPLOYMASTID = D.HREMPLOYMASTID AND A.ODATE = AA.DOCDATE  AND E.BRANCHNAME = AA.BRANCH AND D.IDCARD = AA.EMPID ), 0) OD, NVL((SELECT(0 - SUM(A.STKOPBAL)) SHIFTCNT FROM HRLEAVEREGMAST A  WHERE A.LEAVETYPE = 'EL' AND A.LTYPE <> 'ENC'  AND A.LRDATE = AA.DOCDATE AND A.IDNOCHK = AA.IDCARD  GROUP BY A.IDNOCHK, A.LRDATE),0) EL,NVL((SELECT AA.LHDCNT     FROM HRLEAVEREQMAST A, HRLEAVEREQDETAIL  AA, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E WHERE A.HRLEAVEREQMASTID = AA.HRLEAVEREQMASTID AND A.IDCARD = D.HREMPLOYDETAILSID AND B.WORKNATURE = E.BRANCHMASTID AND A.LTYPE = 'ML' AND AA.LDATE = AA.DOCDATE AND  E.BRANCHNAME = AA.BRANCH AND D.IDCARD = AA.EMPID AND B.HREMPLOYMASTID = D.HREMPLOYMASTID ),0) ML FROM( SELECT A.EMPID, B.FNAME, A.DOCDATE, '' COMTEMP, '' STEMP, A.SHIFTCNT, A.OT, A.EMPID IDCARD, TO_CHAR(A.DOCDATE, 'DD/MM/YYYY') || ' 00:00:00' INDT1, TO_CHAR(A.DOCDATE, 'DD/MM/YYYY') || ' 00:00:00' OUTDT1, B.HREMPLOYMASTID, E.BRANCHNAME BRANCH FROM LOGINLOGOUTREPORT A, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E, GTCOMPMAST F, HRBANDMAST G WHERE A.EMPID = D.IDCARD AND D.BAND = G.HRBANDMASTID AND D.IDCARD = '{empId}' AND A.DOCDATE BETWEEN (SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE(A.SNO1 ='{payPeriod}')) AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE(A.SNO1 = '{payPeriod}')) AND B.HREMPLOYMASTID = D.HREMPLOYMASTID AND E.BRANCHMASTID = B.WORKNATURE AND B.COMPCODE = F.GTCOMPMASTID AND NOT EXISTS(SELECT 'X' FROM( SELECT A.EMPID, B.FNAME, A.DOCDATE, A.TEMPLATE COMTEMP, A.TEMPL STEMP, A.SHIFTCNT, A.OT, A.EMPID IDCARD, CASE WHEN A.INTIME IS NOT NULL AND A.INDT IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(A.INDT || ' ' || A.INTIME, 'DD/MM/YY HH24:MI:SS'), 'DD/MM/YYYY HH24:MI:SS') ELSE '' END INDT1, CASE WHEN A.OUTTIME IS NOT NULL AND A.OUTDT IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(A.OUTDT || ' ' || A.OUTTIME, 'DD/MM/YY HH24:MI:SS') + NUMTODSINTERVAL(A.OT, 'MINUTE'), 'DD/MM/YYYY HH24:MI:SS') ELSE '' END OUTDT1,B.HREMPLOYMASTID FROM BHDATTA A, HREMPLOYMAST B, HREMPLOYDETAILS D WHERE A.EMPMAID = B.HREMPLOYMASTID AND D.IDCARD = '{empId}' AND A.DOCDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID UNION SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, A.ODATE DOCDATE, 'On Duty' COMTEMP, 'On Duty' STEMP, CASE WHEN A.OHDAY = 'I & II' THEN 1 ELSE 0 END SHIFTCNT, 0 OT, TO_NUMBER(D.IDCARD) IDCARD, TO_CHAR(A.ODATE, 'DD/MM/YYYY') INDT1, TO_CHAR(A.ODATE, 'DD/MM/YYYY') OUTDT1, B.HREMPLOYMASTID FROM HRONDUTYDET  A, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E WHERE A.IDCARD = D.HREMPLOYDETAILSID AND B.WORKNATURE = E.BRANCHMASTID AND A.OHDAY = 'I & II' AND A.ODATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(E.BRANCHNAME = '{combobranch.Text}' OR 'ALL' = '{combobranch.Text}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID UNION SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, A.DOCDATE, 'Leave' COMTEMP, 'Leave' STEMP, A.SHIFTCNT,0 OT, TO_NUMBER(D.IDCARD) IDCARD, TO_CHAR(A.DOCDATE, 'DD/MM/YYYY') INDT1, TO_CHAR(A.DOCDATE, 'DD/MM/YYYY') OUTDT1, B.HREMPLOYMASTID FROM(SELECT A.IDCARD, A.IDNOCHK, A.LRDATE DOCDATE, (0 - SUM(A.STKOPBAL)) SHIFTCNT FROM HRLEAVEREGMAST A WHERE A.LRDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') GROUP BY A.IDCARD, A.IDNOCHK, A.LRDATE HAVING(0 - SUM(A.STKOPBAL)) = 1) A, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E WHERE A.IDCARD = B.HREMPLOYMASTID AND B.WORKNATURE = E.BRANCHMASTID AND A.DOCDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID UNION SELECT DISTINCT A.EMPID, A.FNAME, A.DOCDATE, A.COMTEMP, A.STEMP, A.SHIFTCNT,     A.OT, A.IDCARD, A.INDT1, A.OUTDT1, A.HREMPLOYMASTID     FROM( SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, A.NHDATE DOCDATE, A.HOLCAT COMTEMP, A.HOLCAT STEMP, 1 SHIFTCNT, 0 OT, TO_NUMBER(D.IDCARD) IDCARD, TO_CHAR(A.NHDATE, 'DD/MM/YYYY') || ' 00:00:00' INDT1, TO_CHAR(A.NHDATE, 'DD/MM/YYYY') || ' 00:00:00' OUTDT1, B.HREMPLOYMASTID, E.BRANCHNAME BRANCH FROM HRNHDYDETAIL  A, HRNHDYBRANCHDET AA, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E, BHDATTA F, HRBANDMAST G WHERE A.HRNHDYDETAILID = AA.HRNHDYDETAILID AND B.WORKNATURE = E.BRANCHMASTID  AND D.BAND = G.HRBANDMASTID AND AA.BRANCHNAME = E.BRANCHNAME AND D.IDCARD = '{empId}' AND F.EMPID = D.IDCARD AND F.DOCDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND A.NHDATE >= D.DOJ AND(A.NHDATE < D.LASTWORKDAY OR D.LASTWORKDAY IS NULL) AND A.NHDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID ) A UNION SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, AA.LDATE DOCDATE, 'ML' COMTEMP, 'ML' STEMP, 0 SHIFTCNT, 0 OT, TO_NUMBER(D.IDCARD) IDCARD, TO_CHAR(AA.LDATE, 'DD/MM/YYYY') INDT1, TO_CHAR(AA.LDATE, 'DD/MM/YYYY') OUTDT1, B.HREMPLOYMASTID FROM HRLEAVEREQMAST A, HRLEAVEREQDETAIL  AA, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E, HRBANDMAST G WHERE A.HRLEAVEREQMASTID = AA.HRLEAVEREQMASTID AND A.IDCARD = D.HREMPLOYDETAILSID AND D.BAND = G.HRBANDMASTID AND B.WORKNATURE = E.BRANCHMASTID AND A.LTYPE = 'ML' AND D.IDCARD = '{empId}' AND AA.LDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID AND AA.LHDCNT = 1 ) X WHERE X.EMPID = A.EMPID AND X.DOCDATE = A.DOCDATE) UNION SELECT A.EMPID, B.FNAME, A.DOCDATE, A.TEMPLATE COMTEMP, A.TEMPL STEMP, A.SHIFTCNT, A.OT, A.EMPID IDCARD, CASE WHEN A.INTIME IS NOT NULL AND A.INDT IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(A.INDT || ' ' || A.INTIME, 'DD/MM/YY HH24:MI:SS'), 'DD/MM/YYYY HH24:MI:SS') ELSE '' END INDT1, CASE WHEN A.OUTTIME IS NOT NULL AND A.OUTDT IS NOT NULL THEN TO_CHAR(TO_TIMESTAMP(A.OUTDT || ' ' || A.OUTTIME, 'DD/MM/YY HH24:MI:SS') + NUMTODSINTERVAL(A.OT, 'MINUTE'), 'DD/MM/YYYY HH24:MI:SS') ELSE '' END OUTDT1, B.HREMPLOYMASTID, A.BRANCH FROM BHDATTA A, HREMPLOYMAST B, HREMPLOYDETAILS D, HRBANDMAST G WHERE A.EMPMAID = B.HREMPLOYMASTID AND D.BAND = G.HRBANDMASTID AND D.IDCARD = '{empId}' AND A.DOCDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID UNION SELECT DISTINCT A.EMPID, A.FNAME, A.DOCDATE, A.COMTEMP, A.STEMP, A.SHIFTCNT,     A.OT, A.IDCARD, A.INDT1, A.OUTDT1, A.HREMPLOYMASTID, A.BRANCH     FROM( SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, A.NHDATE DOCDATE, A.HOLCAT COMTEMP, A.HOLCAT STEMP, 1 SHIFTCNT, 0 OT, TO_NUMBER(D.IDCARD) IDCARD, TO_CHAR(A.NHDATE, 'DD/MM/YYYY') || ' 00:00:00' INDT1, TO_CHAR(A.NHDATE, 'DD/MM/YYYY') || ' 00:00:00' OUTDT1, B.HREMPLOYMASTID, E.BRANCHNAME BRANCH FROM HRNHDYDETAIL  A, HRNHDYBRANCHDET AA, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E, BHDATTA F, HRBANDMAST G WHERE A.HRNHDYDETAILID = AA.HRNHDYDETAILID AND B.WORKNATURE = E.BRANCHMASTID AND D.BAND = G.HRBANDMASTID  AND AA.BRANCHNAME = E.BRANCHNAME AND B.GENDER = '{combogender.Text}' AND G.BANDID = '{comboband.Text}' AND F.EMPID = D.IDCARD AND A.NHDATE >= D.DOJ AND(A.NHDATE < D.LASTWORKDAY OR D.LASTWORKDAY IS NULL) AND F.DOCDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND (SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND A.NHDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID ) A UNION SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, A.ODATE DOCDATE, 'On Duty' COMTEMP, 'On Duty' STEMP, CASE WHEN A.OHDAY = 'I & II' THEN 1 ELSE 0 END SHIFTCNT, 0 OT, TO_NUMBER(D.IDCARD) IDCARD, TO_CHAR(A.ODATE, 'DD/MM/YYYY') || ' 00:00:00' INDT1, TO_CHAR(A.ODATE, 'DD/MM/YYYY') || ' 00:00:00' OUTDT1, B.HREMPLOYMASTID, E.BRANCHNAME BRANCH FROM HRONDUTYDET  A, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E, HRBANDMAST G WHERE A.IDCARD = D.HREMPLOYDETAILSID AND B.WORKNATURE = E.BRANCHMASTID AND D.BAND = G.HRBANDMASTID AND A.OHDAY = 'I & II' AND D.IDCARD = '{empId}' AND A.ODATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID UNION SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, A.DOCDATE, 'EL' COMTEMP, 'EL' STEMP, A.SHIFTCNT, 0 OT, TO_NUMBER(D.IDCARD) IDCARD, TO_CHAR(A.DOCDATE, 'DD/MM/YYYY') || ' 00:00:00' INDT1, TO_CHAR(A.DOCDATE, 'DD/MM/YYYY') || ' 00:00:00' OUTDT1, B.HREMPLOYMASTID,E.BRANCHNAME BRANCH FROM(SELECT A.IDCARD, A.IDNOCHK, A.LRDATE DOCDATE, (0 - SUM(A.STKOPBAL)) SHIFTCNT FROM HRLEAVEREGMAST A WHERE A.LRDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') GROUP BY A.IDCARD, A.IDNOCHK, A.LRDATE HAVING(0 - SUM(A.STKOPBAL)) = 1) A, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E, HRBANDMAST G WHERE A.IDCARD = B.HREMPLOYMASTID AND B.WORKNATURE = E.BRANCHMASTID AND D.BAND = G.HRBANDMASTID  AND B.GENDER = '{combogender.Text}' AND G.BANDID = '{comboband.Text}' AND A.DOCDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(E.BRANCHNAME = '{combotypename.Text}' OR 'ALL' = '{combotypename.Text}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID UNION SELECT TO_NUMBER(D.IDCARD) EMPID, B.FNAME, AA.LDATE DOCDATE, 'ML' COMTEMP, 'ML' STEMP, 0 SHIFTCNT,0 OT, TO_NUMBER(D.IDCARD) IDCARD,TO_CHAR(AA.LDATE, 'DD/MM/YYYY') || ' 00:00:00' INDT1, TO_CHAR(AA.LDATE, 'DD/MM/YYYY') || ' 00:00:00' OUTDT1, B.HREMPLOYMASTID, E.BRANCHNAME BRANCH FROM HRLEAVEREQMAST A, HRLEAVEREQDETAIL  AA, HREMPLOYMAST B, HREMPLOYDETAILS D, BRANCHMAST E, HRBANDMAST G WHERE A.HRLEAVEREQMASTID = AA.HRLEAVEREQMASTID AND A.IDCARD = D.HREMPLOYDETAILSID AND D.BAND = G.HRBANDMASTID AND B.WORKNATURE = E.BRANCHMASTID AND A.LTYPE = 'ML' AND AA.LHDCNT = 1  AND D.IDCARD = '{empId}' AND AA.LDATE BETWEEN(SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND(SELECT MAX(A.ENDT) TODATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') AND B.HREMPLOYMASTID = D.HREMPLOYMASTID ) AA ) AA JOIN HREMPLOYDETAILS BB ON BB.IDCARD = AA.EMPID JOIN HREMPLOYMAST DD ON BB.HREMPLOYMASTID = DD.HREMPLOYMASTID JOIN GTLOCMAST CC ON CC.GTLOCMASTID = DD.LOCPLACE WHERE AA.EMPID = '{empId}' AND NOT EXISTS(SELECT* FROM ( SELECT A.IDCARD FROM HREMPLOYDETAILS A, HREMPLOYMAST B, GTLOCMAST C, GTDEPTDESGMAST D  WHERE A.HREMPLOYMASTID = B.HREMPLOYMASTID AND B.LOCPLACE = C.GTLOCMASTID  AND A.DEPTNAME = D.GTDEPTDESGMASTID AND (D.DISPNAME IN ('CANTEEN','SECURITY','DRIVER')  OR C.LOCNAME = 'HEAD OFFICE' ) UNION SELECT A.IDCARD FROM HREMPLOYDETAILS A, HREMPLOYMAST B WHERE A.HREMPLOYMASTID = B.HREMPLOYMASTID AND B.EMPTYPE = 'Trainee' UNION SELECT A.IDCARD FROM HREMPLOYDETAILS A, HREMPLOYMAST B WHERE A.HREMPLOYMASTID = B.HREMPLOYMASTID AND A.LASTWORKDAY <= (SELECT MIN(A.STDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}') UNION SELECT A.IDCARD FROM HREMPLOYDETAILS A, HREMPLOYMAST B WHERE A.HREMPLOYMASTID = B.HREMPLOYMASTID AND A.DOJ > (SELECT MAX(A.ENDT) FROMDATE FROM WEEKLYPAYFRQ A WHERE A.SNO1 = '{payPeriod}')  ) ZZ WHERE ZZ.IDCARD = AA.IDCARD ) ORDER BY 1,3";
            DataSet ds3 = Utility.ExecuteSelectQuery(query, "OTSTAMENT");
            return ds3.Tables["OTSTAMENT"];
        }

        private DataTable GetPayroll_Signature(string empId, string compcode)
        {
            string sel2 = "SELECT A.EMPNAME,A.IDCARDNO, A.signature,(SELECT AA.signature FROM ASPTBLEMP AA WHERE AA.ACTIVE='T') as msignature,to_char(c.doj,'dd-MM-YYYY') as dateofjoin,a.BYTESNAME as nameintamil,a.BYTESDESIGN as designintamil   FROM ASPTBLEMP A  JOIN GTCOMPMAST B ON A.COMPCODE=B.GTCOMPMASTID   join HREMPLOYDETAILS c on C.IDCARD=A.IDCARDNO WHERE A.IDCARDNO ='" + empId + "' and  B.COMPCODE = '" + compcode + "' ";// where  A.FINYEAR='" + combofinyear.Text + "' AND  D.compcode='" + combocompcode.Text + "'  and a.payperiod='" + allip.Items[i].SubItems[7].Text + "' AND  C.IDCARD='" + s[1].Substring(7).TrimEnd() + "' order by 1";
            DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLEMP");
           
            return ds2.Tables["ASPTBLEMP"];
        }

        public DataTable GetPayroll_Group(string empId, string payPeriod)
        {


           string query = "SELECT XX.FINYEAR,XX.COMPCODE,XX.COMPNAME,XX.FNAME,XX.IDCARDNO,XX.BRANCH,XX.DESIGNATION,       XX.PAYPERIOD,XX.NOOFDAYS,XX.LOP,XX.EBASIC,XX.EHRA,XX.EDA,XX.ESPL,XX.ERPF,XX.ERESI,XX.EMESSFEES,XX.EOTHDED,XX.ADV,XX.SADV,       XX.BANK,XX.PAYCAT,     XX.IT,XX.EGROSS,XX.NETPAY,XX.BASIC,XX.DA,XX.HRA,XX.SPL,XX.TOTDED,XX.COMPLOGO,XX.DG,XX.PAYCAT1,NVL(YYY.TAKEN,0) TAKEN,     NVL(YYY.CLOSING,0) CLOSING,YYY.IDCARD,NVL(YYY.ELEAVE,0) ELEAVE,XX.EMPTYPE,XX.WALLO  TEST1 ,XX.EWALLO TEST2 ,XX.ETRDED TEST3  FROM (SELECT AA.FINYEAR,AA.COMPCODE,AA.COMPNAME,AA.FNAME,AA.IDCARDNO,AA.BRANCH,AA.DESIGNATION, AA.PAYPERIOD,AA.NOOFDAYS,AA.LOP,AA.EBASIC,AA.EHRA,AA.EDA,AA.ESPL,  AA.ERPF,AA.ERESI,AA.EMESSFEES,AA.EOTHDED,     AA.ADV,AA.SADV,AA.BANK,AA.PAYCAT,                AA.IT,AA.EGROSS,AA.NETPAY,AA.BASIC,AA.DA,AA.HRA,AA.SPL,AA.TOTDED,AA.COMPLOGO,  AA.DG,AA.PAYCAT1,AA.EMPTYPE ,AA.WALLO ,AA.EWALLO,AA.ETRDED  FROM ( SELECT TO_CHAR(TO_DATE(H.MPGDT,'DD/MM/YY'),'DD/MM/YYYY') AS FINYEAR,C.COMPCODE,C.COMPNAME,B.FNAME,B.IDCARDNO,  A.BRANCH,D.DESIGNATION,     A.PAYPERIOD,     A.WDAYS NOOFDAYS,A.MDAYS-A.WDAYS LOP,A.EBASIC, A.EHRA,                 A.EDA,A.ESPL,A.PF ERPF,A.ESI ERESI,  A.MESSFEES EMESSFEES,(A.EOTHDED+ROUND((CASE WHEN A.ECDED > 0 THEN  ( A.WDAYS*(450/A.MDAYS) ) ELSE 0 END),2)+A.ETDED) EOTHDED,A.LOAN ADV,A.SADV,CASE WHEN A.BANK = 'CASH' THEN ' ' ELSE A.BANK END BANK,A.PAYCAT,A.TDSN IT,A.EGROSS, ROUND(A.NETPAY-ROUND((CASE WHEN A.ECDED > 0 THEN  ( A.WDAYS*(450/A.MDAYS) ) ELSE 0 END),2)+A.ECDED+A.ETRDED,0) NETPAY  ,A.BASIC*2 BASIC,A.DA*2 DA,A.HRA*2 HRA,A.SPL*2 SPL,  A.TOTDED+ROUND((CASE WHEN A.ECDED > 0 THEN  ( A.WDAYS*(450/A.MDAYS) ) ELSE 0 END),2)-A.ECDED-A.ETRDED TOTDED  ,(SELECT LOGO FROM EDOCIMAGE1 WHERE IMGNAME='LOGO') COMPLOGO, (SELECT LOGO FROM EDOCIMAGE1      WHERE IMGNAME='DGGM') DG,TO_CHAR(TO_DATE(G.STDT,'DD/MM/YY'),'DD/MM/YYYY')||' TO '||TO_CHAR(TO_DATE(G.ENDT,'DD/MM/YY'),'DD/MM/YYYY') PAYCAT1,'{EMPTYPE}' EMPTYPE ,A.WALLO*2 WALLO   ,   A.EWALLO  ,0 ETRDED   FROM  LOPPLHPAYROLL A JOIN HREMPLOYMAST B ON B.HREMPLOYMASTID=A.EMPID JOIN GTCOMPMAST C ON C.GTCOMPMASTID=B.COMPCODE    JOIN HRDESIGNATIONMAST D ON D.HRDESIGNATIONMASTID=A.DESIGNATION JOIN HREMPLOYDETAILS E ON E.HREMPLOYMASTID=B.HREMPLOYMASTID    JOIN HRBANDMAST F ON F.HRBANDMASTID=E.BAND JOIN MONTHLYPAYFRQ G ON G.PAYPERIOD=A.PAYPERIOD JOIN HRMFRQ H ON H.PAYPERIOD=A.PAYPERIOD WHERE      H.PAYPERIOD='" + payPeriod + "' AND A.PAYPERIOD='" + payPeriod + "' AND A.PCTYPE='ACTUAL' AND B.IDCARDNO='" + empId + "' ) AA )XX,       (SELECT YY.TAKEN,YY.CLOSING,YY.IDCARD,YY.ELEAVE FROM (SELECT  DD.BRANCHNAME BRANCH,AA.IDCARD,BB.FNAME EMPNAME,BB.GENDER,EE.DISPNAME DEPT,FF.DESIGNATION,GG.BANDID ,      AA.SHIFTCNT WDAYS,AA.ELEAVE,AA.TAKEN,AA.TAKEN1,CASE WHEN (AA.ELEAVE-AA.TAKEN1) < 0  THEN 0 ELSE (AA.ELEAVE-AA.TAKEN1) END CLOSING FROM (SELECT A.IDCARD,SUM(A.SHIFTCNT) SHIFTCNT,      ROUND(SUM(A.ELEAVE),3) ELEAVE,SUM(A.TAKEN) TAKEN,SUM(A.TAKEN1) TAKEN1 FROM ( SELECT A.IDCARD,A.SHIFTCNT,0 ELEAVE,0 TAKEN,0 TAKEN1 FROM HREMPWDAY A       UNION ALL       SELECT A.EMPID IDCARD,A.SHIFTCNT,0 ELEAVE,0 TAKEN,0 TAKEN1 FROM HDATTA A,MONTHLYPAYFRQ B,HRLELIGIBLE C WHERE A.PAYPERIOD = B.PAYPERIOD AND B.PAYPERIOD1 = C.PAYPERIOD       AND A.DOCDATE <= (SELECT AA.ENDT FROM MONTHLYPAYFRQ AA WHERE AA.PAYPERIOD='" + payPeriod + "') AND A.SHIFTCNT > 0 UNION ALL SELECT A.EMPID IDCARD,0 SHIFTCNT,      A.SHIFTCNT*A.LEAVE ELEAVE,0 TAKEN,0 TAKEN1 FROM HDATTA A,MONTHLYPAYFRQ B,HRLELIGIBLE C WHERE A.PAYPERIOD = B.PAYPERIOD AND B.PAYPERIOD1 = C.PAYPERIOD       AND A.DOCDATE <= (SELECT AA.ENDT FROM MONTHLYPAYFRQ AA WHERE AA.PAYPERIOD='" + payPeriod + "') AND A.SHIFTCNT > 0       AND B.FINYR = (SELECT AA.FINYR FROM MONTHLYPAYFRQ AA    WHERE AA.PAYPERIOD='" + payPeriod + "')       UNION ALL SELECT TO_NUMBER(A.IDNOCHK) IDCARD,0 SHIFTCNT,0 ELEAVE,(0-SUM(A.STKOPBAL)) TAKEN,(0-SUM(A.STKOPBAL)) TAKEN1 FROM HRLEAVEREGMAST A       WHERE A.LRDATE BETWEEN ( SELECT AA.STDT FROM MONTHLYPAYFRQ AA WHERE AA.PAYPERIOD ='" + payPeriod + "' )       AND (SELECT AA.ENDT FROM MONTHLYPAYFRQ AA WHERE AA.PAYPERIOD='" + payPeriod + "') AND A.LTYPE <> 'ENC'       AND A.FINYEAR = (SELECT AA.FINYR FROM MONTHLYPAYFRQ AA WHERE AA.PAYPERIOD='" + payPeriod + "')         GROUP BY A.IDNOCHK UNION ALL SELECT TO_NUMBER(A.IDNOCHK) IDCARD,0 SHIFTCNT,0 ELEAVE,0 TAKEN,(0-SUM(A.STKOPBAL)) TAKEN1 FROM HRLEAVEREGMAST A       WHERE A.LRDATE < ( SELECT AA.STDT FROM MONTHLYPAYFRQ AA WHERE AA.PAYPERIOD ='" + payPeriod + "' )       AND A.FINYEAR = (SELECT AA.FINYR FROM MONTHLYPAYFRQ AA WHERE AA.PAYPERIOD='" + payPeriod + "')       GROUP BY A.IDNOCHK UNION ALL SELECT TO_NUMBER(A.IDNOCHK) IDCARD,0 SHIFTCNT,0 ELEAVE,0 TAKEN,(0-SUM(A.STKOPBAL)) TAKEN1 FROM HRLEAVEREGMAST A       WHERE A.LRDATE = ( SELECT AA.STDT FROM MONTHLYPAYFRQ AA WHERE AA.PAYPERIOD ='" + payPeriod + "') AND A.LTYPE = 'ENC'       AND ( SELECT TRIM(TO_CHAR(AA.STDT,'DD/MM')) FROM MONTHLYPAYFRQ AA WHERE AA.PAYPERIOD ='" + payPeriod + "') = '01/01'        AND A.FINYEAR = (SELECT AA.FINYR FROM MONTHLYPAYFRQ AA WHERE AA.PAYPERIOD='" + payPeriod + "')         GROUP BY A.IDNOCHK        UNION ALL       SELECT TO_NUMBER(BB.IDCARD) IDCARD,A.OLHDCNT SHIFTCNT,0 ELEAVE,0 TAKEN,0 TAKEN1 FROM HRONDUTYDET A,HREMPLOYDETAILS BB, MONTHLYPAYFRQ B,HRLELIGIBLE C       WHERE A.IDCARD = BB.HREMPLOYDETAILSID AND A.PAYPERIOD = B.PAYPERIOD AND B.PAYPERIOD1 = C.PAYPERIOD       AND A.ODATE  <= (SELECT AA.ENDT FROM MONTHLYPAYFRQ AA WHERE AA.PAYPERIOD='" + payPeriod + "')       UNION ALL       SELECT TO_NUMBER(BB.IDCARD) IDCARD,0 SHIFTCNT,A.OLHDCNT*0.05 ELEAVE,0 TAKEN,0 TAKEN1 FROM HRONDUTYDET A,HREMPLOYDETAILS BB, MONTHLYPAYFRQ B,HRLELIGIBLE C       WHERE A.IDCARD = BB.HREMPLOYDETAILSID AND A.PAYPERIOD = B.PAYPERIOD AND B.PAYPERIOD1 = C.PAYPERIOD       AND A.ODATE  <= (SELECT AA.ENDT FROM MONTHLYPAYFRQ AA WHERE AA.PAYPERIOD='" + payPeriod + "')       AND B.FINYR = (SELECT AA.FINYR FROM MONTHLYPAYFRQ AA WHERE AA.PAYPERIOD='" + payPeriod + "') ) A             GROUP BY A.IDCARD HAVING ( SUM(A.SHIFTCNT) >= 240 AND SUM(A.ELEAVE) > 0 ) ) AA,HREMPLOYMAST BB,HREMPLOYDETAILS CC,BRANCHMAST DD,GTDEPTDESGMAST EE,HRDESIGNATIONMAST FF,      HRBANDMAST GG,GTCOMPMAST HH WHERE AA.IDCARD = CC.IDCARD AND BB.HREMPLOYMASTID = CC.HREMPLOYMASTID AND BB.WORKNATURE = DD.BRANCHMASTID       AND EE.GTDEPTDESGMASTID = CC.DEPTNAME AND FF.HRDESIGNATIONMASTID = CC.DESIGNATION AND GG.HRBANDMASTID = CC.BAND AND HH.GTCOMPMASTID = BB.COMPCODE )  YY ) YYY WHERE XX.IDCARDNO=YYY.IDCARD(+) ORDER BY XX.FNAME";
            DataSet ds3 = Utility.ExecuteSelectQuery(query, "PAYROLL");
            return ds3.Tables["PAYROLL"];
        }
        public DataTable GetPayroll_NotGroup(string empId, string payPeriod)
        {
            string query = @$"SELECT XX.FINYEAR,XX.COMPCODE,XX.COMPNAME,XX.FNAME,XX.IDCARDNO,XX.BRANCH,XX.DESIGNATION,     XX.PAYPERIOD,XX.NOOFDAYS,XX.LOP,XX.EBASIC,XX.EHRA,XX.EDA,XX.ESPL,XX.ERPF,XX.ERESI,XX.EMESSFEES,XX.EOTHDED,XX.ADV,XX.SADV,       XX.BANK,XX.PAYCAT,        XX.IT,XX.EGROSS,XX.NETPAY,XX.BASIC,XX.DA,XX.HRA,XX.SPL,XX.TOTDED,XX.COMPLOGO,XX.DG,XX.PAYCAT1,NVL(YYY.TAKEN, 0) TAKEN,              NVL(YYY.CLOSING, 0) CLOSING,YYY.IDCARD,NVL(YYY.ELEAVE, 0) ELEAVE,XX.EMPTYPE,XX.WALLO TEST1, XX.EWALLO TEST2, XX.ETRDED TEST3  FROM(  SELECT AA.FINYEAR, AA.COMPCODE, AA.COMPNAME, AA.FNAME, AA.IDCARDNO, AA.BRANCH, AA.DESIGNATION, AA.PAYPERIOD, AA.NOOFDAYS, AA.LOP, AA.EBASIC, AA.EHRA, AA.EDA, AA.ESPL, AA.ERPF,  AA.ERESI, AA.EMESSFEES, AA.EOTHDED, AA.ADV, AA.SADV, AA.BANK, AA.PAYCAT, AA.IT, AA.EGROSS, AA.NETPAY, AA.BASIC, AA.DA, AA.HRA, AA.SPL, AA.TOTDED, AA.COMPLOGO, AA.DG, AA.PAYCAT1, AA.EMPTYPE, AA.WALLO, AA.EWALLO, AA.ETRDED FROM(   SELECT TO_CHAR(TO_DATE(G.ENDT, 'DD/MM/YY'), 'DD/MM/YYYY') FINYEAR, C.COMPCODE, C.COMPNAME, B.FNAME, B.IDCARDNO, A.BRANCH, D.DESIGNATION,    A.PAYPERIOD, A.WDAYS NOOFDAYS, A.MDAYS - A.WDAYS LOP, A.EBASIC, A.EHRA, A.EDA, A.ESPL, A.PF ERPF, A.ESI ERESI, A.MESSFEES EMESSFEES, (A.EOTHDED + A.ECDED + A.ETDED) EOTHDED,  A.LOAN ADV, A.SADV, CASE WHEN A.BANK = 'CASH' THEN ' ' ELSE A.BANK END BANK, A.PAYCAT, A.TDSN IT, A.EGROSS, A.NETPAY, A.BASIC * 2 BASIC, A.DA * 2 DA, A.HRA * 2 HRA, A.SPL * 2 SPL,    A.TOTDED, (SELECT LOGO FROM EDOCIMAGE1 WHERE IMGNAME = 'LOGO') COMPLOGO, (SELECT LOGO FROM EDOCIMAGE1  WHERE IMGNAME = 'DGGM') DG,TO_CHAR(TO_DATE(G.STDT, 'DD/MM/YY'), 'DD/MM/YYYY') || ' TO ' || TO_CHAR(TO_DATE(G.ENDT, 'DD/MM/YY'), 'DD/MM/YYYY') PAYCAT1,'SALARY BANK-STATEMENT' EMPTYPE ,    A.WALLO * 2 WALLO   ,    A.EWALLO  ,A.ETRDED FROM  LOPPLHPAYROLL A JOIN HREMPLOYMAST B ON B.HREMPLOYMASTID = A.EMPID     JOIN GTCOMPMAST C ON C.GTCOMPMASTID = B.COMPCODE    JOIN HRDESIGNATIONMAST D ON D.HRDESIGNATIONMASTID = A.DESIGNATION      JOIN HREMPLOYDETAILS E ON E.HREMPLOYMASTID = B.HREMPLOYMASTID     JOIN HRBANDMAST F ON F.HRBANDMASTID = E.BAND      JOIN MONTHLYPAYFRQ G ON G.PAYPERIOD = A.PAYPERIOD      JOIN WEEKLYPAYFRQ H ON H.STDT BETWEEN G.STDT AND G.ENDT  WHERE H.SNO1 = '{payPeriod}'       AND       A.PCTYPE = 'ACTUAL' AND B.IDCARDNO = '{empId}'   ) AA ) XX,   (  SELECT YY.TAKEN,YY.CLOSING,YY.IDCARD,YY.ELEAVE FROM(    SELECT DD.BRANCHNAME BRANCH, AA.IDCARD, BB.FNAME EMPNAME, BB.GENDER, EE.DISPNAME DEPT, FF.DESIGNATION, GG.BANDID , AA.SHIFTCNT WDAYS, AA.ELEAVE, AA.TAKEN, AA.TAKEN1,     CASE WHEN (AA.ELEAVE-AA.TAKEN1) < 0  THEN 0 ELSE(AA.ELEAVE - AA.TAKEN1) END CLOSING FROM( SELECT A.IDCARD, SUM(A.SHIFTCNT) SHIFTCNT, ROUND(SUM(A.ELEAVE), 3) ELEAVE, SUM(A.TAKEN) TAKEN, SUM(A.TAKEN1) TAKEN1 FROM(SELECT A.IDCARD, A.SHIFTCNT, 0 ELEAVE, 0 TAKEN, 0 TAKEN1  FROM HREMPWDAY A UNION ALL SELECT A.EMPID IDCARD, A.SHIFTCNT, 0 ELEAVE, 0 TAKEN, 0 TAKEN1 FROM HDATTA A, WEEKLYPAYFRQ B, HRLELIGIBLE C  WHERE A.DOCDATE BETWEEN B.STDT AND B.ENDT AND A.DOCDATE <= (SELECT AA.ENDT FROM WEEKLYPAYFRQ AA  WHERE AA.SNO1 = '{payPeriod}') AND A.SHIFTCNT > 0 UNION ALL SELECT A.EMPID IDCARD, 0 SHIFTCNT, A.SHIFTCNT * A.LEAVE ELEAVE, 0 TAKEN, 0 TAKEN1  FROM HDATTA A, WEEKLYPAYFRQ B, HRLELIGIBLE C WHERE A.DOCDATE BETWEEN B.STDT AND B.ENDT AND A.DOCDATE <= ( SELECT AA.ENDT FROM WEEKLYPAYFRQ AA WHERE AA.SNO1 = '{payPeriod}') AND A.SHIFTCNT > 0 AND B.FINYR = (SELECT AA.FINYR FROM WEEKLYPAYFRQ AA   WHERE AA.SNO1 = '{payPeriod}') UNION ALL SELECT TO_NUMBER(A.IDNOCHK) IDCARD,0 SHIFTCNT,0 ELEAVE,(0 - SUM(A.STKOPBAL)) TAKEN,(0 - SUM(A.STKOPBAL)) TAKEN1 FROM HRLEAVEREGMAST A WHERE A.LRDATE BETWEEN(SELECT AA.STDT FROM WEEKLYPAYFRQ AA WHERE AA.SNO1 = '{payPeriod}') AND( SELECT AA.ENDT FROM WEEKLYPAYFRQ AA WHERE AA.SNO1 = '{payPeriod}') AND A.LTYPE <> 'ENC' AND A.FINYEAR = (SELECT AA.FINYR FROM WEEKLYPAYFRQ AA WHERE AA.SNO1 = '{payPeriod}') GROUP BY A.IDNOCHK UNION ALL SELECT TO_NUMBER(A.IDNOCHK) IDCARD,0 SHIFTCNT,0 ELEAVE,0 TAKEN,(0 - SUM(A.STKOPBAL)) TAKEN1  FROM HRLEAVEREGMAST A WHERE A.LRDATE < (SELECT AA.STDT FROM WEEKLYPAYFRQ AA WHERE AA.SNO1 = '{payPeriod}' ) AND A.FINYEAR = (  SELECT AA.FINYR FROM WEEKLYPAYFRQ AA WHERE AA.SNO1 = '{payPeriod}') GROUP BY A.IDNOCHK  UNION ALL   SELECT TO_NUMBER(A.IDNOCHK) IDCARD,0 SHIFTCNT,0 ELEAVE,0 TAKEN,(0 - SUM(A.STKOPBAL)) TAKEN1 FROM HRLEAVEREGMAST A WHERE A.LRDATE = ( SELECT AA.STDT FROM WEEKLYPAYFRQ AA WHERE AA.SNO1 = '{payPeriod}' ) AND A.LTYPE = 'ENC' AND(SELECT TRIM(TO_CHAR(AA.STDT, 'DD/MM')) FROM WEEKLYPAYFRQ AA WHERE AA.SNO1 = '{payPeriod}') = '01/01'  AND A.FINYEAR = (SELECT AA.FINYR FROM WEEKLYPAYFRQ AA WHERE AA.SNO1 = '{payPeriod}') GROUP BY A.IDNOCHK UNION ALL SELECT TO_NUMBER(BB.IDCARD) IDCARD,A.OLHDCNT SHIFTCNT,0 ELEAVE,0 TAKEN,0 TAKEN1   FROM HRONDUTYDET A, HREMPLOYDETAILS BB, WEEKLYPAYFRQ B, HRLELIGIBLE C WHERE A.IDCARD = BB.HREMPLOYDETAILSID AND A.ODATE BETWEEN B.STDT AND B.ENDT  AND A.ODATE <= (SELECT AA.ENDT FROM WEEKLYPAYFRQ AA WHERE AA.SNO1 = '{payPeriod}')  UNION ALL   SELECT TO_NUMBER(BB.IDCARD) IDCARD,0 SHIFTCNT,A.OLHDCNT * 0.05 ELEAVE,0 TAKEN,0 TAKEN1 FROM HRONDUTYDET A, HREMPLOYDETAILS BB, WEEKLYPAYFRQ B, HRLELIGIBLE C  WHERE A.IDCARD = BB.HREMPLOYDETAILSID  AND A.ODATE BETWEEN B.STDT AND B.ENDT AND A.ODATE <= (SELECT AA.ENDT FROM WEEKLYPAYFRQ AA      WHERE AA.SNO1 = '{payPeriod}') AND B.FINYR = (SELECT AA.FINYR FROM WEEKLYPAYFRQ AA WHERE AA.SNO1 = '{payPeriod}') ) A  GROUP BY A.IDCARD HAVING(SUM(A.SHIFTCNT) >= 240 AND SUM(A.ELEAVE) > 0 ) ) AA,HREMPLOYMAST BB, HREMPLOYDETAILS CC,BRANCHMAST DD, GTDEPTDESGMAST EE,HRDESIGNATIONMAST FF, HRBANDMAST GG,GTCOMPMAST HH WHERE AA.IDCARD = CC.IDCARD AND BB.HREMPLOYMASTID = CC.HREMPLOYMASTID AND BB.WORKNATURE = DD.BRANCHMASTID AND EE.GTDEPTDESGMASTID = CC.DEPTNAME AND FF.HRDESIGNATIONMASTID = CC.DESIGNATION AND GG.HRBANDMASTID = CC.BAND AND HH.GTCOMPMASTID = BB.COMPCODE )  YY    ) YYY      WHERE XX.IDCARDNO = YYY.IDCARD(+) ORDER BY XX.FNAME";        
         
            DataSet ds4 = Utility.ExecuteSelectQuery(query, "PAYROLL");
            return ds4.Tables["PAYROLL"];
        }
        public void DownLoads()
        {
            try
            {
                if (allip.Items.Count > 0)
                {
                    Class.Users.UserTime = 0;
                    i = 0; string folderLocation1 = "D:\\PaySlipDownload\\" + combopayperiod.Text + "\\";
                    progressBar2.Minimum = 0; int cnt = 0; int k = 0;
                    progressBar2.Maximum = allip.Items.Count;
                    Cursor = Cursors.WaitCursor; rd1.PrintOptions.PrinterName = printDialog1.PrinterSettings.PrinterName;
                    if (combostatement.Text == "SALARYSLIP")
                    {
                        crystalReportViewer1.ReportSource = null; crystalReportViewer1.Refresh();
                        Cursor = Cursors.WaitCursor;
                        progressBar2.Minimum = 0;
                        progressBar2.Maximum = allip.Items.Count;
                        progressBar2.Maximum = allip.Items.Count; lblprogross4.Visible = true;

                        foreach (ListViewItem item in allip.Items)
                        {
                            
                            string empId = item.SubItems[3].Text;
                            string payPeriod = item.SubItems[7].Text;
                            string compcode = Class.Users.HCompcode;
                            if (IsGroupUser(Class.Users.HUserName))
                            {
                                dtprint1 = GetPayroll_Group(empId, payPeriod);
                            }
                            else
                            {
                                dtprint1 = GetPayroll_NotGroup(empId, payPeriod);

                            }                         
                            if (dtprint1.Rows.Count > 0)
                            {
                                dtprint2 = GetPayroll_Signature(empId, compcode);
                                dtprint3 = GetPayroll_OT1(empId, payPeriod);
                                dtprint4 = GetPayroll_OT(empId, payPeriod);
                                rd1.Database.Tables["DataTable1"].SetDataSource(dtprint1);
                                rd1.Database.Tables["DataTable2"].SetDataSource(dtprint2);
                                rd1.Database.Tables["DataTable3"].SetDataSource(dtprint3);
                                rd1.Database.Tables["DataTable4"].SetDataSource(dtprint4);

                                if (!Directory.Exists(folderLocation1)) { Directory.CreateDirectory(folderLocation1); }

                                rd1.ExportToDisk(ExportFormatType.PortableDocFormat, folderLocation1 + item.Index.ToString() + " - " + item.SubItems[3].Text + "  - " + item.SubItems[5].Text + "  " + "PaySlip.pdf");

                            }
                            decimal per = Convert.ToDecimal(100 / GenFun.ToDecimal(allip.Items.Count)) * item.Index;
                            lblprogross4.Text = " Downloading.... : " + ((int)per).ToString("N0") + " %" + " IDCardNo:   " + item.SubItems[3].Text + "  ----- " + item.SubItems[5].Text + "           Count  :  " + item.Index + "   Total Record:   " + allip.Items.Count.ToString();
                            lblprogross4.Refresh();
                            progressBar2.Value = item.Index + 1;Class.Users.LoginTime = 1800;
                        }

                     

                        Cursor = Cursors.Default; progressBar2.Value = 0; lblprogross4.Text = ""; lblprogross4.Visible = false;

                        mas.pop("PaySlip Download Completed","in D drive","");
                    }
                   

                    Cursor = Cursors.Default;
                    lblprogross4.Text = ""; progressBar2.Value = 0; empty();
                }
                else
                {
                    mas.pop("Pls Select Checkbox in ListView .","","");
                }
            }catch(Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        




        }
        private void datasave()
        {
            //string ins = "insert into ASPTBLPRINT(FINYEAR,COMPCODE,PAYPERIOD,IDCARDNO,EMPNAME,IPADDRESS,CREATEDON,CREATEDBY,MODIFIEDON,DATETIME)values('" + Class.Users.Finyear + "','" + Class.Users.COMPCODE + "','" + allip.Items[i].SubItems[7].Text + "','" + allip.Items[i].SubItems[3].Text + "','" + Class.Users.HostelName + "','" + Class.Users.IPADDRESS + "','" + System.DateTime.Now.ToString() + "','" + Class.Users.HUserName + "','" + System.DateTime.Now.ToString() + "',to_date('" + System.DateTime.Now.ToString("dd-MM-yyyy hh:mm:ss") + "', 'dd-MM-yyyy HH:mi:ss'))";
            //Utility.ExecuteNonQuery(ins);
        }
     

        public void Prints()
    {
            if (printDialog1.ShowDialog() == DialogResult.OK)//,b.intime,b.intime1, b.outtime,b.outtime1,c.address,c.pincode 
            {
                if (dtprint1.Rows.Count == 0)
                {
                    MessageBox.Show("No data found.");
                    return;
                }

                string folderLocation = Path.Combine(
                    Environment.GetFolderPath(Environment.SpecialFolder.Desktop),
                    "PaySlip-Download"
                );

                if (!Directory.Exists(folderLocation))
                {
                    Directory.CreateDirectory(folderLocation);
                }

                // Safe file name
                string empName = dtprint1.Rows[0]["FNAME"].ToString();
                string payPeriod = dtprint1.Rows[0]["PAYPERIOD"].ToString();

                string safeName = string.Join("_", empName.Split(Path.GetInvalidFileNameChars()));

                string filePath = Path.Combine(folderLocation,
                    $"{safeName}_{payPeriod}_PaySlip.pdf");

                using (var reportdocument = new CrystalDecisions.CrystalReports.Engine.ReportDocument())
                {
                    reportdocument.Load(Path.Combine(Application.StartupPath, "Report\\Lovely\\OTReport.rpt"));

                    // ✔ Correct mapping (verify with your report)
                    reportdocument.Database.Tables["DataTable1"].SetDataSource(dtprint1);
                    reportdocument.Database.Tables["DataTable2"].SetDataSource(dtprint2);
                    reportdocument.Database.Tables["DataTable3"].SetDataSource(dtprint3);
                    reportdocument.Database.Tables["DataTable4"].SetDataSource(dtprint4);
                    // ✔ Export PDF
                    reportdocument.ExportToDisk(ExportFormatType.PortableDocFormat, filePath);

                    // ✔ Print
                    reportdocument.PrintOptions.PrinterName = printDialog1.PrinterSettings.PrinterName;
                    reportdocument.PrintToPrinter(
                        printDialog1.PrinterSettings.Copies,
                        printDialog1.PrinterSettings.Collate,
                        printDialog1.PrinterSettings.FromPage,
                        printDialog1.PrinterSettings.ToPage
                    );

                    reportdocument.Close();
                }
                               datasave();empty();
                dtprint1 = null;
                dtprint2 = null; dtprint3 = null;

            }

        }

    private void txtsearch1_TextChanged(object sender, EventArgs e)
    {
        try
        {
                Class.Users.UserTime = 0;
                int item0 = 0; listView2.Items.Clear();
            if (txtsearch1.Text.Length >= 1)
            {
                foreach (ListViewItem item in listfilter2.Items)
                {
                    ListViewItem list = new ListViewItem();
                    if (listfilter2.Items[item0].SubItems[3].ToString().Contains(txtsearch1.Text.ToUpper()) || listfilter2.Items[item0].SubItems[4].ToString().Contains(txtsearch1.Text.ToUpper()) || listfilter2.Items[item0].SubItems[5].ToString().Contains(txtsearch1.Text.ToUpper()))
                    {
                        list.Text = listfilter2.Items[item0].SubItems[0].Text;
                        list.SubItems.Add(listfilter2.Items[item0].SubItems[1].Text);
                        list.SubItems.Add(listfilter2.Items[item0].SubItems[2].Text);
                        list.SubItems.Add(listfilter2.Items[item0].SubItems[3].Text);
                        list.SubItems.Add(listfilter2.Items[item0].SubItems[4].Text);
                        list.SubItems.Add(listfilter2.Items[item0].SubItems[5].Text);
                        list.SubItems.Add(listfilter2.Items[item0].SubItems[6].Text);
                        list.SubItems.Add(listfilter2.Items[item0].SubItems[7].Text);
                        if (item0 % 2 == 0)
                        {
                            list.BackColor = Color.WhiteSmoke;
                        }
                        else
                        {
                            list.BackColor = Color.White;
                        }
                        listView2.Items.Add(list);


                    }
                    item0++;
                }
                lbltotal2.Text = "Total Count: " + listView2.Items.Count;
            }
            else
            {
                ListView ll = new ListView();
                listView2.Items.Clear();
                foreach (ListViewItem item in listfilter2.Items)
                {
                    this.listView2.Items.Add((ListViewItem)item.Clone());
                    if (item0 % 2 == 0)
                    {
                        item.BackColor = Color.WhiteSmoke;
                    }
                    else
                    {
                        item.BackColor = Color.White;
                    }

                    item0++;
                }
                lbltotal2.Text = "Total Count: " + listView2.Items.Count;
            }


        }
        catch (Exception ex)
        {
            //MessageBox.Show("---" + ex.ToString());
        }
    }
         
      
        private void combomonth_SelectedIndexChanged(object sender, EventArgs e)
        {
           
        }



    private void combobranch_SelectedIndexChanged(object sender, EventArgs e)
    {
        try
        {
            if (Convert.ToInt64(combobranch.SelectedValue) > 0)
            {
                Cursor = Cursors.WaitCursor;
                    string sel1 = "SELECT '' PAYMONTH FROM DUAL  union all select PAYMONTH from ( SELECT A.SNO1 as PAYMONTH FROM WEEKLYPAYFRQ A JOIN GTCOMPMAST B ON A.COMPCODE=B.COMPCODE WHERE B.COMPCODE='" + Class.Users.HCompcode + "'  ORDER BY A.STDT";
                DataSet ds1 = Utility.ExecuteSelectQuery(sel1, "WEEKLYPAYFRQ");
                DataTable dt1 = ds1.Tables["WEEKLYPAYFRQ"];
                combopayperiod.DisplayMember = "PAYMONTH";
                combopayperiod.ValueMember = "PAYMONTH";
                combopayperiod.DataSource = dt1;
                Cursor = Cursors.Default;
            }
        }
        catch (Exception ex)
        {

        }
    }

  
    private void refreshToolStripMenuItem1_Click(object sender, EventArgs e)
    {

    }


        private void chkall_CheckedChanged(object sender, EventArgs e)
        {
            if (chkall.Checked == true)
            {
                int listCount = listView2.Items.Count;
                foreach (ListViewItem item in listView2.Items)
                {
                    item.Checked = true;
                }
            }
            else
            {
                foreach (ListViewItem item in listView2.Items)
                {
                    item.Checked = false;
                }
            }
        }

   

   
    private void listView2_ItemChecked(object sender, ItemCheckedEventArgs e)
    {
        try
        {
            
            
                ListViewItem it2 = new ListViewItem();
                if (e.Item.Checked == true)
                {
                    e.Item.SubItems[0].Text = "T";
                    e.Item.BackColor = System.Drawing.SystemColors.MenuHighlight;
                    e.Item.ForeColor = Color.White;
                    it2.SubItems.Add(e.Item.SubItems[1].Text);
                    it2.SubItems.Add(e.Item.SubItems[2].Text);
                    it2.SubItems.Add(e.Item.SubItems[3].Text);
                    it2.SubItems.Add(e.Item.SubItems[4].Text);
                    it2.SubItems.Add(e.Item.SubItems[5].Text);
                    it2.SubItems.Add(e.Item.SubItems[6].Text);
                    it2.SubItems.Add(e.Item.SubItems[7].Text);
                    allip.Items.Add(it2);
                    Cursor = Cursors.Default;
                   
                }
                if (e.Item.Checked == false && e.Item.SubItems[0].Text == "T")
                {

                    e.Item.SubItems[0].Text = "F"; e.Item.BackColor = System.Drawing.SystemColors.ControlLightLight;
                    e.Item.ForeColor = Color.Black;
                    for (int c = 0; c < allip.Items.Count; c++)
                    {

                        if (e.Item.SubItems[3].Text == allip.Items[c].SubItems[3].Text)
                        {
                            allip.Items[c].Remove();
                            e.Item.SubItems[0].Text = "";
                            c--;
                           
                        }
                    }

                }

           
           
        }
        catch (Exception ex) { MessageBox.Show("       ---  " + e.Item.ToString() + "             ======================" + ex.ToString()); }
    }

   
   
  

  
 

    private void checkword_CheckedChanged(object sender, EventArgs e)
    {
      
    }

    private void lblprogross4_Click(object sender, EventArgs e)
    {

    }

        
        public void Saves()
        {
           
        }

       

        public void Searchs()
        {
            
        }

        public void Deletes()
        {
           
        }

        public void Imports()
        {
            
        }

       

        public void ChangePasswords()
        {
            
        }       
     
        public void ChangeSkins()
        {
            
        }

        public void Logins()
        {
            
        }

        public void GlobalSearchs()
        {
          
        }

        public void TreeButtons()
        {
            
        }

        public void Exit()
        {
            this.Hide();
            GlobalVariables.MdiPanel.Show();
            News();
            GlobalVariables.HeaderName.Text = "";
            GlobalVariables.TabCtrl.TabPages.RemoveAt(GlobalVariables.TabCtrl.SelectedIndex);

        }

        private void chechide_CheckedChanged(object sender, EventArgs e)
        {
            
        }

        private void combostatement_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void buttonok_Click(object sender, EventArgs e)
        {
            Cursor = Cursors.WaitCursor; 
            GridLoad();
            Cursor = Cursors.Default; Class.Users.UserTime = 0;
        }

        private void label2_Click(object sender, EventArgs e)
        {

        }

        private void label5_Click(object sender, EventArgs e)
        {

        }

        public void Searchs(int id)
        {
            throw new NotImplementedException();
        }

        public void Deletes(int id)
        {
            throw new NotImplementedException();
        }

        public void ReadOnlys()
        {
            throw new NotImplementedException();
        }

        private void buttonok_Click_1(object sender, EventArgs e)
        {

        }
    }
}
