using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;

namespace Pinnacle.ReportFormate
{
    public partial class TokenReport : Form, ToolStripAccess
    {
        public TokenReport()
        {
            InitializeComponent();
           
            Class.Users.IPADDRESS = GenFun.GetLocalIPAddress();
            Class.Users.CREATED = Convert.ToDateTime(System.DateTime.Now.ToString("dd/MM/yyyy") + " " + System.DateTime.Now.ToLongTimeString());
            Class.Users.SysDate = Convert.ToString(System.DateTime.Now.ToString("dd/MM/yyyy"));
            Class.Users.SysTime = Convert.ToString(DateTime.Now.ToLongTimeString().ToString());
            GlobalVariables.HeaderName.Text = Class.Users.ScreenName; GlobalVariables.CurrentForm = this;
            butheader.BackColor = Class.Users.BackColors;
            usercheck(Class.Users.HCompcode, Class.Users.HUserName, Class.Users.ScreenName);

            this.BackColor = Class.Users.BackColors;
        }

        public void usercheck(string s, string ss, string sss)
        {

            DataTable dt1 = sm.headerdropdowns(s, ss, sss);
            int cnt = dt1.Rows.Count;
            if (cnt >= 1)
            {
                if (dt1.Rows[0]["Menuname"].ToString() == Class.Users.ScreenName)
                {
                    for (int r = 0; r < dt1.Rows.Count; r++)
                    {
                        if (dt1.Rows[r]["DELETES"].ToString() == "T") { GlobalVariables.Deletes.Visible = false; checkdatabase.Visible = true; } else { GlobalVariables.Deletes.Visible = false; checkdatabase.Visible = false; }

                    }
                }



            }
            else
            {
                MessageBox.Show("No Screen Rights Defined .Pls Contact Your Administrator...");
            }


        }

        string MON = "";
        private static TokenReport _instance;
        Models.Master mas = new Models.Master();
        Models.UserRights sm = new Models.UserRights();
        byte[] bytes; private int rowIndex = 0;
        public static TokenReport Instance
        {
            get { if (_instance == null) _instance = new TokenReport(); GlobalVariables.CurrentForm = _instance; return _instance; }

        }
        Report.CompanyVehicleCrystalReport cv = new Report.CompanyVehicleCrystalReport();
        Report.TokenDetails rd = new Report.TokenDetails();
        Report.AGF.DateWise datewise = new Report.AGF.DateWise();
        public void ReadOnlys()
        {

        }
        private void TokenDetails_Load(object sender, EventArgs e)
        {
            //DataTable dt1 = mas.findcomcode1(Class.Users.HCompcode);
            //if (dt1.Rows.Count > 0)
            //{
            //    combocompcode.DisplayMember = "COMPCODE";
            //    combocompcode.ValueMember = "GTCOMPMASTID";
            //    combocompcode.DataSource = dt1;
            //    combocompcode.Text = "";combocompcode.SelectedIndex = -1;
            //}
            comboitem();
            bunkfind(); comboitem();
            this.txtsearch.Focus(); comboformate.SelectedIndex = 1;
            //combobunk.Text = "";combobunk.SelectedIndex = -1;
            todate.Value = DateTime.Today.AddDays(0);
            frmdate.Value = DateTime.Today.AddDays(-1);
            //combocompcode_SelectedIndexChanged(sender, e);
        }
        void comboitem()
        {
            try
            {
                string sel1 = "SELECT 0 AS GTGENITEMMASTID, '' AS ITEMNAME FROM DUAL UNION ALL SELECT 1 AS GTGENITEMMASTID, 'TOKEN CANCEL' AS ITEMNAME FROM DUAL UNION ALL  SELECT 2 AS GTGENITEMMASTID, 'ALL' AS ITEMNAME FROM DUAL UNION ALL   SELECT 3 AS GTGENITEMMASTID, 'FULL' AS ITEMNAME FROM DUAL UNION ALL  SELECT DISTINCT  A.GTGENITEMMASTID,A.ITEMNAME FROM GTGENITEMMAST A WHERE A.FT='T' AND A.ACTIVE='T'";
                DataSet ds = Utility.ExecuteSelectQuery(sel1, "GTGENITEMMAST");
                DataTable dt = ds.Tables["GTGENITEMMAST"];
                combocompcode.ValueMember = "GTGENITEMMASTID";
                combocompcode.DisplayMember = "ITEMNAME";
                combocompcode.DataSource = dt;
            }
            catch (Exception EX) { }
        }
        void bunkfind()
        {

          
            DataTable dt = mas.bunkfind(Class.Users.HCompcode);
            if (dt.Rows.Count == 1)
            {
                combobunk.DisplayMember = "BUNKNAME";
                combobunk.ValueMember = "ASPTBLPETMASID";
                combobunk.DataSource = dt; combobunk.Enabled = false;
            }
            else
            {
                combobunk.DisplayMember = "BUNKNAME";
                combobunk.ValueMember = "ASPTBLPETMASID";
                combobunk.DataSource = dt; combobunk.Enabled = true;
            }
        }
        private void News_Click(object sender, EventArgs e)
        {

        }

        private void crystalReportViewer1_Load(object sender, EventArgs e)
        {

        }

        private void combocompcode_SelectedIndexChanged(object sender, EventArgs e)
        {
            //try
            //{
            //    DataTable dt2 = new DataTable();
            //    dt2 = null;
            //    if (combocompcode.Text == "TOKEN CANEL")
            //    {
            //        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,X.FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,A.REMARKS   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='T'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.ITEMNAME='" + combocompcode.Text + "' AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS ORDER BY 1";

            //       // string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,X.LITRES,X.FUELRATE2 ,X.BUNKNAME,X.ACTIVE, SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='T'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.ITEMNAME='" + combocompcode.Text + "' AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE ORDER BY 1";
            //        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
            //        dt2 = ds2.Tables["ASPTBLVEHTOKEN"];
            //        crystalReportViewer1.ReportSource = null;
            //        rd.SetDataSource(dt2);

            //        crystalReportViewer1.ReportSource = rd;

            //        crystalReportViewer1.Refresh();return;
            //    }
            //    if (combocompcode.Text == "DIESEL")
            //    {
            //        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,X.FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,A.REMARKS   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.ITEMNAME='" + combocompcode.Text + "' AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS ORDER BY 1";

            //       // string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,X.LITRES,X.FUELRATE2 ,X.BUNKNAME,X.ACTIVE, SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.ITEMNAME='" + combocompcode.Text + "' AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE ORDER BY 1";
            //        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
            //        dt2 = ds2.Tables["ASPTBLVEHTOKEN"];
            //        crystalReportViewer1.ReportSource = null;
            //        rd.SetDataSource(dt2);
                  
            //        crystalReportViewer1.ReportSource = rd;

            //        crystalReportViewer1.Refresh();return;
            //    }
            //    if (combocompcode.Text == "PETROL")
            //    {
            //        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,X.FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,A.REMARKS   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.ITEMNAME='" + combocompcode.Text + "' AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS ORDER BY 1";

            //        //string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,X.LITRES,X.FUELRATE2 ,X.BUNKNAME,X.ACTIVE, SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.ITEMNAME='" + combocompcode.Text + "' AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE ORDER BY 1";
            //        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
            //        dt2 = ds2.Tables["ASPTBLVEHTOKEN"];
            //        crystalReportViewer1.ReportSource = null;
            //        rd.SetDataSource(dt2);

            //        crystalReportViewer1.ReportSource = rd;

            //        crystalReportViewer1.Refresh();return;
            //    }
            //    if (combocompcode.Text == "2T OIL")
            //    {
            //        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,X.FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  B.ITEMDESC,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,A.REMARKS   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME AND B.ITEMDESC='" + combocompcode.Text + "') X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy')  AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS ORDER BY 1";

            //        //string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,X.LITRES,X.FUELRATE2 ,X.BUNKNAME,X.ACTIVE, SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.ITEMNAME='" + combocompcode.Text + "' AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE ORDER BY 1";

            //        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
            //        dt2 = ds2.Tables["ASPTBLVEHTOKEN"];
            //        crystalReportViewer1.ReportSource = null;
            //        rd.SetDataSource(dt2);

            //        crystalReportViewer1.ReportSource = rd;

            //        crystalReportViewer1.Refresh();return;
            //    }
            //    if (combocompcode.Text == "FULL")
            //    {
            //        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,X.FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  B.ITEMDESC,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,A.REMARKS   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME AND B.ITEMDESC='" + combocompcode.Text + "') X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy')  AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS ORDER BY 1";

            //        //string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,X.LITRES,X.FUELRATE2 ,X.BUNKNAME,X.ACTIVE, SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.ITEMNAME='" + combocompcode.Text + "' AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE ORDER BY 1";
            //        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
            //        dt2 = ds2.Tables["ASPTBLVEHTOKEN"];
            //        crystalReportViewer1.ReportSource = null;
            //        rd.SetDataSource(dt2);

            //        crystalReportViewer1.ReportSource = rd;

            //        crystalReportViewer1.Refresh();
            //    }
            //    if (combocompcode.Text == "ALL")
            //    {
            //        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,X.FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,A.REMARKS   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS ORDER BY 1";

            //      //  string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,X.LITRES,X.FUELRATE2 ,X.BUNKNAME,X.ACTIVE, SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.BUNKNAME='" + combobunk.Text + "'   GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE ORDER BY 1";
            //        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
            //        dt2 = ds2.Tables["ASPTBLVEHTOKEN"];

            //        rd.SetDataSource(dt2);
            //        crystalReportViewer1.ReportSource = null;
            //        crystalReportViewer1.ReportSource = rd;

            //        crystalReportViewer1.Refresh();
            //    }
               
            //}
            //catch (Exception EX)
            //{ MessageBox.Show(EX.Message); }
           
        }

        private void txtsearch_TextChanged(object sender, EventArgs e)
        {
            try
            {
                Class.Users.UserTime = 0;
                if (txtsearch.Text.Length > 6)
                {
                    //  crystalReportViewer1.Refresh(); crystalReportViewer1.ReportSource = null;
                    string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,ROUND(X.FUELRATE2,2) AS FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, ROUND(SUM(X.LITRES*X.FUELRATE2),2) AS TOTAL ,X.TODATE,to_char(X.ASPTBLVEHTOKENID1)as ASPTBLVEHTOKENID1 FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME  AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME  AND ZAA.COMPCODE=D.GTCOMPMASTID  AND ZAA.COMPCODE=D.GTCOMPMASTID AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,A.REMARKS,'" + MON + "' AS TODATE ,A.TOTALKM AS ASPTBLVEHTOKENID1  FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='T'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "'  AND   X.VEHICLENO LIKE'%" + txtsearch.Text + "%'  GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS,X.TODATE ,X.ASPTBLVEHTOKENID1 ORDER BY 4";

                    DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLHOSTELGATEPASS");
                    DataTable dt2 = ds2.Tables["ASPTBLHOSTELGATEPASS"];
                    rd.SetDataSource(dt2);

                    crystalReportViewer1.ReportSource = rd;


                    lblcount.Refresh();
                    lblcount.Text = "Total Count  :" + dt2.Rows.Count.ToString(); txtsearch.Select();
                }
                //else
                //{
                //    string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,X.LITRES,X.FUELRATE2 ,SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME ) X   WHERE  X.COMPCODE='" + Class.Users.HCompcode + "' AND X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') and TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2 ORDER BY 1";
                //    DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
                //    DataTable dt2 = ds2.Tables["ASPTBLVEHTOKEN"];

                //    rd.SetDataSource(dt2);
                //    crystalReportViewer1.ReportSource = null;
                //    crystalReportViewer1.ReportSource = rd;

                //    crystalReportViewer1.Refresh();
                //}

            }
            catch (Exception EX)
            { MessageBox.Show(EX.Message); }
            txtsearch.Select();
        }

        private void butView_Click(object sender, EventArgs e)
        {

            Class.Users.UserTime = 0;
            try
            {
                MON = CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(frmdate.Value.Month) + "-" + frmdate.Value.Year;
                if (tabControl1.SelectedTab.Text == "TokenDetails")
                {

                    if (combocompcode.Text == "TOKEN CANEL")
                    {
                        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,ROUND(X.FUELRATE2,2) AS FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, ROUND(SUM(X.LITRES*X.FUELRATE2),2) AS TOTAL ,X.TODATE,to_char(X.ASPTBLVEHTOKENID1)as ASPTBLVEHTOKENID1 FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME  AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME  AND ZAA.COMPCODE=D.GTCOMPMASTID  AND ZAA.COMPCODE=D.GTCOMPMASTID AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,A.REMARKS,'" + MON + "' AS TODATE ,b.KM AS ASPTBLVEHTOKENID1  FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='T'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy')  AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS,X.TODATE ,X.ASPTBLVEHTOKENID1 ORDER BY 4";

                        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
                        DataTable dt2 = ds2.Tables["ASPTBLVEHTOKEN"];
                        crystalReportViewer1.ReportSource = null;
                        rd.SetDataSource(dt2);

                        crystalReportViewer1.ReportSource = rd;

                        crystalReportViewer1.Refresh(); lblcount.Refresh();
                        lblcount.Text = "Total Count  :" + dt2.Rows.Count.ToString(); return;
                    }
                    if (txtsearch.Text == "" && combocompcode.Text != "")
                    {
                        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,ROUND(X.FUELRATE2,2) AS FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, ROUND(SUM(X.LITRES*X.FUELRATE2),2) AS TOTAL,X.TODATE,to_char(X.ASPTBLVEHTOKENID1)as ASPTBLVEHTOKENID1 FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, J.MNNAME1 AS  DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME   AND AA.ASPTBLFUELRATEMASDETID = ( SELECT MAX(ZAA.ASPTBLFUELRATEMASDETID) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME  AND ZAA.COMPCODE=D.GTCOMPMASTID AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,A.REMARKS ,'" + MON + "' AS TODATE ,A.TOTALKM AS ASPTBLVEHTOKENID1  FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME join GTDEPTDESGMAST j on   J.GTDEPTDESGMASTID=F.DEPTNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.ITEMNAME='" + combocompcode.Text + "' AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS,X.TODATE,X.ASPTBLVEHTOKENID1 ORDER BY 4";

                        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
                        DataTable dt2 = ds2.Tables["ASPTBLVEHTOKEN"];
                        crystalReportViewer1.ReportSource = null;
                        rd.SetDataSource(dt2); 

                        crystalReportViewer1.ReportSource = rd;

                        crystalReportViewer1.Refresh(); lblcount.Refresh();
                        lblcount.Text = "Total Count  :" + dt2.Rows.Count.ToString(); return;
                    }
                    if (txtsearch.Text != "" && combocompcode.Text != "")
                    {
                        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,ROUND(X.FUELRATE2,2) AS FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, ROUND(SUM(X.LITRES*X.FUELRATE2),2) AS TOTAL,X.TODATE,to_char(X.ASPTBLVEHTOKENID1)as ASPTBLVEHTOKENID1 FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, J.MNNAME1 AS  DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME   AND AA.ASPTBLFUELRATEMASDETID = ( SELECT MAX(ZAA.ASPTBLFUELRATEMASDETID) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME  AND ZAA.COMPCODE=D.GTCOMPMASTID AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,A.REMARKS ,'" + MON + "' AS TODATE ,A.TOTALKM AS ASPTBLVEHTOKENID1  FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME join GTDEPTDESGMAST j on   J.GTDEPTDESGMASTID=F.DEPTNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.ITEMNAME='" + combocompcode.Text + "' AND X.BUNKNAME='" + combobunk.Text + "' AND X.VEHICLENO LIKE'%" + txtsearch.Text + "%' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS,X.TODATE,X.ASPTBLVEHTOKENID1 ORDER BY 4";

                        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
                        DataTable dt2 = ds2.Tables["ASPTBLVEHTOKEN"];
                        crystalReportViewer1.ReportSource = null;
                        rd.SetDataSource(dt2);

                        crystalReportViewer1.ReportSource = rd;

                        crystalReportViewer1.Refresh(); lblcount.Refresh();
                        lblcount.Text = "Total Count  :" + dt2.Rows.Count.ToString(); return;
                    }
                    if (combocompcode.Text == "ALL" || combocompcode.Text == "")
                    {

                        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,ROUND(X.FUELRATE2,2) AS FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, ROUND(SUM(X.LITRES*X.FUELRATE2),2) AS TOTAL,X.TODATE,to_char(X.ASPTBLVEHTOKENID1)as ASPTBLVEHTOKENID1,X.LITRES1 FROM  (  SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  (   SELECT  AA.VEHICLENO   FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID          JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE    WHERE  AA.HRVEHMASTID=A.VEHICLENO          UNION ALL           SELECT  BA.VEHICLENO FROM ASPTBLVEHMAS BA      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO     ) AS VEHICLENO , (     SELECT  AB.VEHTYPE   FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID          JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE       WHERE  AA.HRVEHMASTID=A.VEHICLENO      UNION ALL       SELECT  BA.VCATEGORY as VEHTYPE FROM ASPTBLVEHMAS BA   JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO     ) AS VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, J.MNNAME1 AS  DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2         FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME  AND AA.ASPTBLFUELRATEMASDETID = ( SELECT MAX(ZAA.ASPTBLFUELRATEMASDETID) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME  AND ZAC.ITEMNAME = AC.ITEMNAME  AND ZAA.COMPCODE=D.GTCOMPMASTID AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,                A.REMARKS ,'" + MON + "' AS TODATE ,A.TOTALKM AS ASPTBLVEHTOKENID1,F.MIDCARD AS LITRES1  FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'   JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME       JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE   AND  I.ASPTBLPETMASID=A.BUNKNAME join GTDEPTDESGMAST j on   J.GTDEPTDESGMASTID=F.DEPTNAME ) X WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy')  AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS,X.TODATE,X.ASPTBLVEHTOKENID1,X.LITRES1 ORDER BY 5";
                        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
                        DataTable dt2 = ds2.Tables["ASPTBLVEHTOKEN"];

                        rd.SetDataSource(dt2);
                        crystalReportViewer1.ReportSource = null;
                        crystalReportViewer1.Refresh();
                        crystalReportViewer1.ReportSource = rd;
                        lblcount.Refresh();
                        lblcount.Text = "Total Count  :" + dt2.Rows.Count.ToString(); return;

                    }

                }
                if (tabControl1.SelectedTab.Text == "Date Wise")
                {

                    if (combocompcode.Text == "TOKEN CANEL")
                    {
                        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  SUBSTR(X.TOKENDATE,0,10) AS TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,ROUND(X.FUELRATE2,2) AS FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, ROUND(SUM(X.LITRES*X.FUELRATE2),2) AS TOTAL ,X.TODATE,to_char(X.ASPTBLVEHTOKENID1)as ASPTBLVEHTOKENID1 FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME  AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME  AND ZAA.COMPCODE=D.GTCOMPMASTID  AND ZAA.COMPCODE=D.GTCOMPMASTID AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,A.REMARKS,'" + MON + "' AS TODATE ,b.KM AS ASPTBLVEHTOKENID1  FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='T'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy')  AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS,X.TODATE ,X.ASPTBLVEHTOKENID1 ORDER BY 1";

                        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
                        DataTable dt2 = ds2.Tables["ASPTBLVEHTOKEN"];
                        crystalReportViewer2.ReportSource = null;
                        datewise.SetDataSource(dt2);

                        crystalReportViewer2.ReportSource = datewise;

                        crystalReportViewer2.Refresh(); lblcount.Refresh();
                        lblcount.Text = "Total Count  :" + dt2.Rows.Count.ToString(); return;
                    }
                    if (txtsearch.Text == "" && combocompcode.Text != "")
                    {
                        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,   SUBSTR(X.TOKENDATE,0,10) AS TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,ROUND(X.FUELRATE2,2) AS FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, ROUND(SUM(X.LITRES*X.FUELRATE2),2) AS TOTAL,X.TODATE,to_char(X.ASPTBLVEHTOKENID1)as ASPTBLVEHTOKENID1 FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, J.MNNAME1 AS  DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME   AND AA.ASPTBLFUELRATEMASDETID = ( SELECT MAX(ZAA.ASPTBLFUELRATEMASDETID) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME  AND ZAA.COMPCODE=D.GTCOMPMASTID AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,A.REMARKS ,'" + MON + "' AS TODATE ,A.TOTALKM AS ASPTBLVEHTOKENID1  FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME join GTDEPTDESGMAST j on   J.GTDEPTDESGMASTID=F.DEPTNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.ITEMNAME='" + combocompcode.Text + "' AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS,X.TODATE,X.ASPTBLVEHTOKENID1 ORDER BY 1";

                        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
                        DataTable dt2 = ds2.Tables["ASPTBLVEHTOKEN"];
                        crystalReportViewer2.ReportSource = null;
                        datewise.SetDataSource(dt2);

                        crystalReportViewer2.ReportSource = datewise;

                        crystalReportViewer2.Refresh(); lblcount.Refresh();
                        lblcount.Text = "Total Count  :" + dt2.Rows.Count.ToString(); return;
                    }
                    if (txtsearch.Text != "" && combocompcode.Text != "")
                    {
                        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,   SUBSTR(X.TOKENDATE,0,10) AS TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,ROUND(X.FUELRATE2,2) AS FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, ROUND(SUM(X.LITRES*X.FUELRATE2),2) AS TOTAL,X.TODATE,to_char(X.ASPTBLVEHTOKENID1)as ASPTBLVEHTOKENID1 FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, J.MNNAME1 AS  DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME   AND AA.ASPTBLFUELRATEMASDETID = ( SELECT MAX(ZAA.ASPTBLFUELRATEMASDETID) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME  AND ZAA.COMPCODE=D.GTCOMPMASTID AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,A.REMARKS ,'" + MON + "' AS TODATE ,A.TOTALKM AS ASPTBLVEHTOKENID1  FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME join GTDEPTDESGMAST j on   J.GTDEPTDESGMASTID=F.DEPTNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.ITEMNAME='" + combocompcode.Text + "' AND X.BUNKNAME='" + combobunk.Text + "' AND X.VEHICLENO LIKE'%" + txtsearch.Text + "%' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS,X.TODATE,X.ASPTBLVEHTOKENID1 ORDER BY 1";

                        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
                        DataTable dt2 = ds2.Tables["ASPTBLVEHTOKEN"];
                        crystalReportViewer2.ReportSource = null;
                        datewise.SetDataSource(dt2);

                        crystalReportViewer2.ReportSource = datewise;

                        crystalReportViewer2.Refresh(); lblcount.Refresh();
                        lblcount.Text = "Total Count  :" + dt2.Rows.Count.ToString(); return;
                    }
                    if (combocompcode.Text == "ALL" || combocompcode.Text == "")
                    {

                        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  SUBSTR(X.TOKENDATE,0,10) AS TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,ROUND(X.FUELRATE2,2) AS FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, ROUND(SUM(X.LITRES*X.FUELRATE2),2) AS TOTAL,X.TODATE,to_char(X.ASPTBLVEHTOKENID1)as ASPTBLVEHTOKENID1,X.LITRES1 FROM  (  SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  (   SELECT  AA.VEHICLENO   FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID          JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE    WHERE  AA.HRVEHMASTID=A.VEHICLENO          UNION ALL           SELECT  BA.VEHICLENO FROM ASPTBLVEHMAS BA      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO     ) AS VEHICLENO , (     SELECT  AB.VEHTYPE   FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID          JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE       WHERE  AA.HRVEHMASTID=A.VEHICLENO      UNION ALL       SELECT  BA.VCATEGORY as VEHTYPE FROM ASPTBLVEHMAS BA   JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO     ) AS VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, J.MNNAME1 AS  DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2         FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME  AND AA.ASPTBLFUELRATEMASDETID = ( SELECT MAX(ZAA.ASPTBLFUELRATEMASDETID) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME  AND ZAC.ITEMNAME = AC.ITEMNAME  AND ZAA.COMPCODE=D.GTCOMPMASTID AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,                A.REMARKS ,'" + MON + "' AS TODATE ,A.TOTALKM AS ASPTBLVEHTOKENID1,F.MIDCARD AS LITRES1  FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'   JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME       JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE   AND  I.ASPTBLPETMASID=A.BUNKNAME join GTDEPTDESGMAST j on   J.GTDEPTDESGMASTID=F.DEPTNAME ) X WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy')  AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS,X.TODATE,X.ASPTBLVEHTOKENID1,X.LITRES1 ORDER BY 1";
                        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
                        DataTable dt2 = ds2.Tables["ASPTBLVEHTOKEN"];

                        datewise.SetDataSource(dt2);
                        crystalReportViewer2.ReportSource = null;
                        crystalReportViewer2.Refresh();
                        crystalReportViewer2.ReportSource = datewise;
                        lblcount.Refresh();
                        lblcount.Text = "Total Count  :" + dt2.Rows.Count.ToString(); return;

                    }

                }
            }
            catch (Exception EX)
            { MessageBox.Show(EX.Message); }


        }

        public void DownLoads()
        {           

            if (comboformate.Text != "")
            {

                DialogResult result = MessageBox.Show("Do you want to '" + comboformate.Text + "' Formate ??", "" + comboformate.Text + "PRINT OUT", MessageBoxButtons.OKCancel, MessageBoxIcon.Information);
                if (result.Equals(DialogResult.OK))
                {
                    if (combocompcode.Text == "AGF")
                    {
                        switch (comboformate.Text)
                        {
                            case "Word":
                                cv.ExportToDisk(ExportFormatType.WordForWindows, "d:\\'" + combocompcode.Text + "'CompanyVehicleOnly.doc");
                                break;

                            case "Excel":                               
                                cv.ExportToDisk(ExportFormatType.ExcelWorkbook, "d:\\'" + combocompcode.Text + "'CompanyVehicleOnly.xls");
                                break;
                            case "PDF":
                                cv.ExportToDisk(ExportFormatType.PortableDocFormat, "d:\\'" + combocompcode.Text + "'CompanyVehicleOnly.pdf");
                                break;

                            case "CSV":
                                cv.ExportToDisk(ExportFormatType.CharacterSeparatedValues, "d:\\'" + combocompcode.Text + "'CompanyVehicleOnly.csv");
                                break;
                        }
                        combocompcode.SelectedIndex = -1; combocompcode.Text = "";
                    }
                    else
                    {
                        if (tabControl1.SelectedTab.Text == "TokenDetails")
                        {
                            switch (comboformate.Text)
                            {
                                case "Word":
                                    rd.ExportToDisk(ExportFormatType.WordForWindows, "d:\\'" + combocompcode.Text + "'TokenDetails.doc");
                                    break;

                                case "Excel":
                                    // formatType = ExportFormatType.Excel;
                                    rd.ExportToDisk(ExportFormatType.ExcelWorkbook, "d:\\'" + combocompcode.Text + "'TokenDetails.xls");
                                    break;

                                case "PDF":
                                    rd.ExportToDisk(ExportFormatType.PortableDocFormat, "d:\\'" + combocompcode.Text + "'TokenDetails.pdf");
                                    break;

                                case "CSV":
                                    rd.ExportToDisk(ExportFormatType.CharacterSeparatedValues, "d:\\'" + combocompcode.Text + "'TokenDetails.csv");
                                    break;
                            }
                        }
                        if (tabControl1.SelectedTab.Text == "Date Wise")
                        {
                            switch (comboformate.Text)
                            {
                                case "Word":
                                    datewise.ExportToDisk(ExportFormatType.WordForWindows, "d:\\'" + combocompcode.Text + "'DateWise.doc");
                                    break;

                                case "Excel":
                                    // formatType = ExportFormatType.Excel;
                                    datewise.ExportToDisk(ExportFormatType.ExcelWorkbook, "d:\\'" + combocompcode.Text + "'DateWise.xls");
                                    break;

                                case "PDF":
                                    datewise.ExportToDisk(ExportFormatType.PortableDocFormat, "d:\\'" + combocompcode.Text + "'DateWise.pdf");
                                    break;

                                case "CSV":
                                    datewise.ExportToDisk(ExportFormatType.CharacterSeparatedValues, "d:\\'" + combocompcode.Text + "'DateWise.csv");
                                    break;
                            }
                        }
                    }
                }
                else
                {

                }
            }
            else
            {
                MessageBox.Show("Pls Select Combo Box Value");
            }
        }

        private void refreshToolStripMenuItem_Click(object sender, EventArgs e)
        {

        }

    

        private void label5_Click(object sender, EventArgs e)
        {

        }

        public void Prints()
        {
            try
            {
                if (printDialog1.ShowDialog() == DialogResult.OK)
                {
                    MON = CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(frmdate.Value.Month) + "-" + frmdate.Value.Year;

                    try
                    {
                        if (combocompcode.Text == "TOKEN CANEL")
                        {
                            //string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,ROUND(X.FUELRATE2,2) AS FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, ROUND(SUM(X.LITRES*X.FUELRATE2),2) AS TOTAL,X.TODATE  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, J.MNNAME1 AS  DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME  AND ZAA.COMPCODE=D.GTCOMPMASTID AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,A.REMARKS ,'" + MON + "' AS TODATE  FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='T'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME join GTDEPTDESGMAST j on   J.GTDEPTDESGMASTID=F.DEPTNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS,X.TODATE ORDER BY 1";
                            //DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
                            //DataTable dt2 = ds2.Tables["ASPTBLVEHTOKEN"];
                            //CrystalDecisions.CrystalReports.Engine.ReportDocument reportdocument = new CrystalDecisions.CrystalReports.Engine.ReportDocument();
                            //reportdocument.Load(Application.StartupPath + "\\Report\\TokenDetails.rpt");
                            //reportdocument.SetDataSource(dt2);
                            rd.PrintOptions.PrinterName = printDialog1.PrinterSettings.PrinterName;
                            rd.PrintToPrinter(printDialog1.PrinterSettings.Copies, printDialog1.PrinterSettings.Collate, printDialog1.PrinterSettings.FromPage, printDialog1.PrinterSettings.ToPage);

                        }
                        else
                        {
                           // string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,TO_NUMBER(X.LITRES) AS LITRES,ROUND(X.FUELRATE2,2) AS FUELRATE2 ,X.BUNKNAME,X.ACTIVE,X.REMARKS AS FROMDATE, ROUND(SUM(X.LITRES*X.FUELRATE2),2) AS TOTAL ,X.TODATE FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, J.MNNAME1 AS  DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME  AND ZAA.COMPCODE=D.GTCOMPMASTID AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME,I.BUNKNAME AS ACTIVE,A.REMARKS,'" + MON + "' AS TODATE   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME join GTDEPTDESGMAST j on   J.GTDEPTDESGMASTID=F.DEPTNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME,X.ACTIVE,X.REMARKS,X.TODATE ORDER BY 1";

                           ////string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,X.LITRES,X.FUELRATE2 ,SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  WHERE  D.COMPCODE='" + Class.Users.HCompcode + "' AND A.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') and TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy')) X GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2 ORDER BY 1";
                           // DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
                           // DataTable dt2 = ds2.Tables["ASPTBLVEHTOKEN"];

                            //CrystalDecisions.CrystalReports.Engine.ReportDocument reportdocument = new CrystalDecisions.CrystalReports.Engine.ReportDocument();
                            //reportdocument.Load(Application.StartupPath + "\\Report\\TokenDetails.rpt");
                            //reportdocument.SetDataSource(dt2);
                            rd.PrintOptions.PrinterName = printDialog1.PrinterSettings.PrinterName;
                            rd.PrintToPrinter(printDialog1.PrinterSettings.Copies, printDialog1.PrinterSettings.Collate, printDialog1.PrinterSettings.FromPage, printDialog1.PrinterSettings.ToPage);

                        }
                    }
                    catch (Exception EX)
                    { MessageBox.Show(EX.Message); }

               

                }
            }

            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void comboformate_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void combobunk_SelectedIndexChanged(object sender, EventArgs e)
        {
            //try
            //{
            //    DataTable dt2 = new DataTable();
            //    dt2 = null;
            //    if (combocompcode.Text != "" && combobunk.Text != "")
            //    {
            //        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,X.LITRES,X.FUELRATE2 ,X.BUNKNAME, SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy')  AND X.ITEMNAME='" + combocompcode.Text + "'  AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME ORDER BY 1";
            //        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
            //        dt2 = ds2.Tables["ASPTBLVEHTOKEN"];
            //        crystalReportViewer1.ReportSource = null;
            //        rd.SetDataSource(dt2);

            //        crystalReportViewer1.ReportSource = rd;

            //        crystalReportViewer1.Refresh();
            //    }
            //    if (combocompcode.Text == "" && combobunk.Text != "") {
            //        string sel2 = "SELECT X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME as EMPNAME, X.DEPT,  X.ITEMNAME,X.LITRES,X.FUELRATE2 ,X.BUNKNAME, SUM(X.LITRES*X.FUELRATE2) TOTAL  FROM  ( SELECT A.ASPTBLVEHTOKENID, D.COMPCODE,A.TOKENNO,  A.TOKENDATE,  ( SELECT  AA.VEHICLENO    FROM HRVEHMAST AA  JOIN HRVEHTYPEMAST Ab on AA.VEHICLETYPE=AB.HRVEHTYPEMASTID     JOIN GTCOMPMAST AC ON AC.GTCOMPMASTID=AA.COMPCODE      WHERE  AA.HRVEHMASTID=A.VEHICLENO   UNION ALL        SELECT  BA.VEHICLENO  FROM ASPTBLVEHMAS BA  JOIN HRVEHTYPEMAST BB ON BA.VEHICLETYPE=BB.HRVEHTYPEMASTID      JOIN GTCOMPMAST BC ON BC.GTCOMPMASTID=BA.COMPCODE   WHERE  BA.ASPTBLVEHMASID=A.VEHICLENO ) AS VEHICLENO, G.VEHTYPE ,CONCAT(E.fname, concat('-', F.MIDCARD))  AS FNAME, F.DEPT,  H.ITEMNAME,  CASE B.LITRES  WHEN  'FULL' THEN '0'    ELSE B.LITRES END as LITRES,    (SELECT max(AA.FUELRATE2) AS FUELRATE2 FROM ASPTBLFUELRATEMASDET AA JOIN GTCOMPMAST AB  ON AA.COMPCODE = AB.GTCOMPMASTID JOIN GTGENITEMMAST AC ON AC.GTGENITEMMASTID = AA.ITEMNAME    WHERE AB.COMPCODE = D.COMPCODE AND AC.GTGENITEMMASTID = AA.ITEMNAME AND AA.BUNKNAME=A.BUNKNAME  AND AC.ITEMNAME = H.ITEMNAME AND AA.FUELDATE = ( SELECT MAX(ZAA.FUELDATE) FROM ASPTBLFUELRATEMASDET ZAA  JOIN GTCOMPMAST ZAB  ON ZAA.COMPCODE = ZAB.GTCOMPMASTID JOIN GTGENITEMMAST ZAC ON ZAC.GTGENITEMMASTID = ZAA.ITEMNAME   WHERE ZAB.COMPCODE = AB.COMPCODE AND ZAA.BUNKNAME=A.BUNKNAME AND ZAC.ITEMNAME = AC.ITEMNAME AND ZAA.FUELDATE <= A.TOKENDATE  )  )  AS FUELRATE2,I.BUNKNAME   FROM  ASPTBLVEHTOKEN A     JOIN ASPTBLVEHTOKENDET B ON A.ASPTBLVEHTOKENID=B.ASPTBLVEHTOKENID   AND A.TOKENCANCEL='F'    JOIN GTCOMPMAST D ON D.GTCOMPMASTID=A.COMPCODE  JOIN HREMPLOYMAST E ON E.HREMPLOYMASTID=A.EMPNAME    JOIN hremploydetails F ON F.HREMPLOYMASTID=E.HREMPLOYMASTID  join HRVEHTYPEMAST G on G.HRVEHTYPEMASTid=A.VEHICLETYPE   JOIN GTGENITEMMAST H ON H.GTGENITEMMASTID=B.ITEMNAME  JOIN ASPTBLPETMAS I ON I.COMPCODE=D.GTCOMPMASTID AND I.COMPCODE=A.COMPCODE  AND  I.ASPTBLPETMASID=A.BUNKNAME) X  WHERE X.COMPCODE='" + Class.Users.HCompcode + "' AND   X.TOKENDATE between TO_DATE('" + frmdate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy') AND TO_DATE('" + todate.Value.ToString("dd-MM-yyyy") + "','dd-MM-yyyy')    AND X.BUNKNAME='" + combobunk.Text + "' GROUP BY X.ASPTBLVEHTOKENID, X.COMPCODE,X.TOKENNO,  X.TOKENDATE,X.VEHICLENO, X.VEHTYPE ,X.FNAME, X.DEPT,  X.ITEMNAME,X.LITRES, X.FUELRATE2,X.BUNKNAME ORDER BY 1";
            //        DataSet ds2 = Utility.ExecuteSelectQuery(sel2, "ASPTBLVEHTOKEN");
            //        dt2 = ds2.Tables["ASPTBLVEHTOKEN"];
            //        crystalReportViewer1.ReportSource = null;
            //        rd.SetDataSource(dt2);

            //        crystalReportViewer1.ReportSource = rd;

            //        crystalReportViewer1.Refresh();
            //    }

            //}
            //catch (Exception EX)
            //{ MessageBox.Show(EX.Message); }
        }

        public void News()
        {
            butheader.BackColor = Class.Users.BackColors;
            
          
            this.BackColor = Class.Users.BackColors;
        }

        public void Saves()
        {
           
        }

        public void Searchs()
        {
           
        }

        public void Deletes()
        {
           
        }

        public void Imports()
        {
           
        }

        public void Pdfs()
        {
           
        }

        public void ChangePasswords()
        {
           
        }

     
        public void ChangeSkins()
        {
           
        }

        public void Logins()
        {
           
        }

        public void GlobalSearchs()
        {
           
        }

        public void TreeButtons()
        {
           
        }

        public void Exit()
        {
            GlobalVariables.MdiPanel.Show();
            News();
            GlobalVariables.HeaderName.Text = "";
            GlobalVariables.TabCtrl.TabPages.RemoveAt(GlobalVariables.TabCtrl.SelectedIndex);
            this.Hide();
        }

        public void GridLoad()
        {
           
        }

        public void Searchs(int id)
        {
            throw new NotImplementedException();
        }

        public void Deletes(int id)
        {
            throw new NotImplementedException();
        }

        private void checkdatabase_CheckedChanged(object sender, EventArgs e)
        {
            mas.DatabaseCheck(checkdatabase);
        }

        private void tabControl1_SelectedIndexChanged(object sender, EventArgs e)
        {
            if(tabControl1.SelectedTab == tabControl1.TabPages["tabPage1"])
            {
                 butView_Click(sender,e);
               
            }
            if (tabControl1.SelectedTab == tabControl1.TabPages["tabPage2"])
            {
                butView_Click(sender, e);
              
            }
        }
    }
}
